load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "protocol",
    srcs = [
        "prepare.pb.go",
        "prepare_grpc.pb.go",
        "toolprotocol.pb.go",
        "toolprotocol_grpc.pb.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/planning/tool/protocol",
    visibility = ["//:__subpackages__"],
    deps = [
        "//schema",
        "//std/types",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//runtime/protoimpl",
        "@org_golang_google_protobuf//types/known/anypb",
    ],
)
