// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: internal/planning/tool/protocol/prepare.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PrepareServiceClient is the client API for PrepareService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrepareServiceClient interface {
	Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error)
}

type prepareServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrepareServiceClient(cc grpc.ClientConnInterface) PrepareServiceClient {
	return &prepareServiceClient{cc}
}

func (c *prepareServiceClient) Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error) {
	out := new(PrepareResponse)
	err := c.cc.Invoke(ctx, "/foundation.provision.tool.protocol.PrepareService/Prepare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrepareServiceServer is the server API for PrepareService service.
// All implementations should embed UnimplementedPrepareServiceServer
// for forward compatibility
type PrepareServiceServer interface {
	Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error)
}

// UnimplementedPrepareServiceServer should be embedded to have forward compatible implementations.
type UnimplementedPrepareServiceServer struct {
}

func (UnimplementedPrepareServiceServer) Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}

// UnsafePrepareServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrepareServiceServer will
// result in compilation errors.
type UnsafePrepareServiceServer interface {
	mustEmbedUnimplementedPrepareServiceServer()
}

func RegisterPrepareServiceServer(s grpc.ServiceRegistrar, srv PrepareServiceServer) {
	s.RegisterService(&PrepareService_ServiceDesc, srv)
}

func _PrepareService_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrepareServiceServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/foundation.provision.tool.protocol.PrepareService/Prepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrepareServiceServer).Prepare(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PrepareService_ServiceDesc is the grpc.ServiceDesc for PrepareService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrepareService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "foundation.provision.tool.protocol.PrepareService",
	HandlerType: (*PrepareServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _PrepareService_Prepare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/planning/tool/protocol/prepare.proto",
}
