load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "git",
    srcs = [
        "branch.go",
        "env.go",
        "repo.go",
        "rungit.go",
        "status.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/git",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/console",
        "//internal/fnerrors",
        "@org_golang_x_exp//slices",
    ],
)
