load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "core",
    srcs = [
        "checker.go",
        "debughandler.go",
        "endpoints.go",
        "env.go",
        "healthz.go",
        "init.go",
        "instantiation.go",
        "lifecycle.go",
        "server.go",
    ],
    importpath = "namespacelabs.dev/foundation/std/go/core",
    visibility = ["//visibility:public"],
    deps = [
        "//framework/rpcerrors",
        "//framework/rpcerrors/multierr",
        "//framework/runtime",
        "//schema",
        "//schema/runtime",
        "//std/core/types",
        "@com_github_gorilla_mux//:mux",
        "@com_github_philopon_go_toposort//:go-toposort",
        "@com_github_prometheus_client_golang//prometheus/promhttp",
        "@com_github_rs_zerolog//:zerolog",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_protobuf//proto",
        "@org_uber_go_atomic//:atomic",
    ],
)
