// This file was automatically generated by Foundation.
// DO NOT EDIT. To update, re-run `fn generate`.

package core

import (
	"context"
)

type _checkProvideDebugHandler func(context.Context, *DebugHandlerArgs) (DebugHandler, error)

var _ _checkProvideDebugHandler = ProvideDebugHandler

type _checkProvideLivenessCheck func(context.Context, *LivenessCheckArgs) (Check, error)

var _ _checkProvideLivenessCheck = ProvideLivenessCheck

type _checkProvideReadinessCheck func(context.Context, *ReadinessCheckArgs) (Check, error)

var _ _checkProvideReadinessCheck = ProvideReadinessCheck

type _checkProvideServerInfo func(context.Context, *ServerInfoArgs) (*ServerInfo, error)

var _ _checkProvideServerInfo = ProvideServerInfo

var (
	Package__u30kfm = &Package{
		PackageName: "namespacelabs.dev/foundation/std/go/core",
	}
)
