// Copyright 2022 Namespace Labs Inc; All rights reserved.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: orchestration/proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	runtime "namespacelabs.dev/foundation/schema/runtime"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AreServicesReadyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deployable *runtime.Deployable `protobuf:"bytes,1,opt,name=deployable,proto3" json:"deployable,omitempty"`
	Namespace  string              `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *AreServicesReadyRequest) Reset() {
	*x = AreServicesReadyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orchestration_proto_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AreServicesReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreServicesReadyRequest) ProtoMessage() {}

func (x *AreServicesReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_proto_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreServicesReadyRequest.ProtoReflect.Descriptor instead.
func (*AreServicesReadyRequest) Descriptor() ([]byte, []int) {
	return file_orchestration_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *AreServicesReadyRequest) GetDeployable() *runtime.Deployable {
	if x != nil {
		return x.Deployable
	}
	return nil
}

func (x *AreServicesReadyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type AreServicesReadyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ready   bool   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AreServicesReadyResponse) Reset() {
	*x = AreServicesReadyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orchestration_proto_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AreServicesReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreServicesReadyResponse) ProtoMessage() {}

func (x *AreServicesReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_proto_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreServicesReadyResponse.ProtoReflect.Descriptor instead.
func (*AreServicesReadyResponse) Descriptor() ([]byte, []int) {
	return file_orchestration_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *AreServicesReadyResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *AreServicesReadyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_orchestration_proto_service_proto protoreflect.FileDescriptor

var file_orchestration_proto_service_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x11, 0x6e, 0x73, 0x6c, 0x2e, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x72,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x61, 0x62, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7e, 0x0a, 0x17, 0x41, 0x72, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x45, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x61, 0x62, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x0a, 0x64,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x4a, 0x0a, 0x18, 0x41, 0x72, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0x83, 0x01, 0x0a, 0x14, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6b, 0x0a, 0x10,
	0x41, 0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79,
	0x12, 0x2a, 0x2e, 0x6e, 0x73, 0x6c, 0x2e, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x6e,
	0x73, 0x6c, 0x2e, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x41, 0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x61, 0x64,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6c, 0x61, 0x62, 0x73, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x66,
	0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orchestration_proto_service_proto_rawDescOnce sync.Once
	file_orchestration_proto_service_proto_rawDescData = file_orchestration_proto_service_proto_rawDesc
)

func file_orchestration_proto_service_proto_rawDescGZIP() []byte {
	file_orchestration_proto_service_proto_rawDescOnce.Do(func() {
		file_orchestration_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_orchestration_proto_service_proto_rawDescData)
	})
	return file_orchestration_proto_service_proto_rawDescData
}

var file_orchestration_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_orchestration_proto_service_proto_goTypes = []interface{}{
	(*AreServicesReadyRequest)(nil),  // 0: nsl.orchestration.AreServicesReadyRequest
	(*AreServicesReadyResponse)(nil), // 1: nsl.orchestration.AreServicesReadyResponse
	(*runtime.Deployable)(nil),       // 2: foundation.schema.runtime.Deployable
}
var file_orchestration_proto_service_proto_depIdxs = []int32{
	2, // 0: nsl.orchestration.AreServicesReadyRequest.deployable:type_name -> foundation.schema.runtime.Deployable
	0, // 1: nsl.orchestration.OrchestrationService.AreServicesReady:input_type -> nsl.orchestration.AreServicesReadyRequest
	1, // 2: nsl.orchestration.OrchestrationService.AreServicesReady:output_type -> nsl.orchestration.AreServicesReadyResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_orchestration_proto_service_proto_init() }
func file_orchestration_proto_service_proto_init() {
	if File_orchestration_proto_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_orchestration_proto_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AreServicesReadyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orchestration_proto_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AreServicesReadyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orchestration_proto_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestration_proto_service_proto_goTypes,
		DependencyIndexes: file_orchestration_proto_service_proto_depIdxs,
		MessageInfos:      file_orchestration_proto_service_proto_msgTypes,
	}.Build()
	File_orchestration_proto_service_proto = out.File
	file_orchestration_proto_service_proto_rawDesc = nil
	file_orchestration_proto_service_proto_goTypes = nil
	file_orchestration_proto_service_proto_depIdxs = nil
}
