load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "api",
    srcs = [
        "buildplatform.go",
        "creds.go",
        "dial.go",
        "registry.go",
        "rpc.go",
        "types.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/providers/nscloud/api",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/jsonreparser",
        "//internal/artifacts/oci",
        "//internal/compute",
        "//internal/console",
        "//internal/fnapi",
        "//internal/fnerrors",
        "//internal/providers/nscloud/api/public",
        "//internal/providers/nscloud/endpoint",
        "//std/tasks",
        "@com_github_bcicen_jstream//:jstream",
        "@com_github_cenkalti_backoff//:backoff",
        "@com_github_google_go_containerregistry//pkg/authn",
        "@com_github_gorilla_websocket//:websocket",
        "@com_github_jpillora_chisel//share/cnet",
        "@dev_namespacelabs_go_ids//:go-ids",
        "@dev_namespacelabs_integrations//proto/namespace/cloud/builder/v1beta",
        "@dev_namespacelabs_integrations//proto/namespace/cloud/compute/v1beta",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//types/known/emptypb",
        "@org_golang_google_protobuf//types/known/timestamppb",
        "@org_golang_x_exp//maps",
        "@org_golang_x_exp//slices",
        "@org_uber_go_atomic//:atomic",
    ],
)
