load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "oci",
    srcs = [
        "annotate.go",
        "canonical.go",
        "estargz.go",
        "fetchimage.go",
        "fromfs.go",
        "imageid.go",
        "ingest.go",
        "localcopy.go",
        "localimage.go",
        "makeimage.go",
        "makeindex.go",
        "makelayer.go",
        "mergeimage.go",
        "name.go",
        "partialimage.go",
        "prebuilt.go",
        "publishimage.go",
        "push.go",
        "readfiles.go",
        "reference.go",
        "remote.go",
        "resolveimage.go",
        "scratch.go",
        "transport.go",
        "types.go",
        "types.pb.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/artifacts/oci",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/artifacts",
        "//internal/artifacts/contentstore",
        "//internal/build/registry",
        "//internal/compute",
        "//internal/console",
        "//internal/executor",
        "//internal/fnerrors",
        "//internal/fnfs/maketarfs",
        "//internal/fnfs/tarfs",
        "//internal/parsing/platform",
        "//internal/ssh",
        "//internal/tcache",
        "//internal/uniquestrings",
        "//internal/versions",
        "//internal/workspace/dirs",
        "//schema",
        "//std/tasks",
        "@com_github_cenkalti_backoff_v4//:backoff",
        "@com_github_containerd_stargz_snapshotter_estargz//:estargz",
        "@com_github_dustin_go_humanize//:go-humanize",
        "@com_github_google_go_containerregistry//pkg/authn",
        "@com_github_google_go_containerregistry//pkg/name",
        "@com_github_google_go_containerregistry//pkg/v1:pkg",
        "@com_github_google_go_containerregistry//pkg/v1/empty",
        "@com_github_google_go_containerregistry//pkg/v1/mutate",
        "@com_github_google_go_containerregistry//pkg/v1/partial",
        "@com_github_google_go_containerregistry//pkg/v1/remote",
        "@com_github_google_go_containerregistry//pkg/v1/tarball",
        "@com_github_google_go_containerregistry//pkg/v1/types",
        "@com_github_klauspost_compress//zstd",
        "@com_github_opencontainers_image_spec//specs-go/v1:specs-go",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//runtime/protoimpl",
        "@org_golang_x_exp//maps",
    ],
)
