load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "fncue",
    srcs = [
        "any.go",
        "attrs.go",
        "cue.go",
        "errors.go",
        "format.go",
        "imports.go",
        "keywords.go",
        "partial.go",
        "workspace.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/frontend/fncue",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/rpcerrors/multierr",
        "//internal/console",
        "//internal/fnerrors",
        "//internal/fnfs",
        "//internal/fnfs/memfs",
        "//internal/protos",
        "//schema",
        "@io_k8s_utils//strings/slices",
        "@org_cuelang_go//cue",
        "@org_cuelang_go//cue/ast",
        "@org_cuelang_go//cue/ast/astutil",
        "@org_cuelang_go//cue/build",
        "@org_cuelang_go//cue/cuecontext",
        "@org_cuelang_go//cue/errors",
        "@org_cuelang_go//cue/format",
        "@org_cuelang_go//cue/parser",
        "@org_cuelang_go//cue/token",
        "@org_golang_google_protobuf//encoding/protojson",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//reflect/protoreflect",
    ],
)
