image: gitpod/workspace-full
checkoutLocation: ns-gitpod-k3s
tasks:
  - name: prepare k3s
    command: |
      .gitpod/prepare-k3s.sh
  - name: kernel dev environment
    init: |
      sudo apt update -y
      sudo apt upgrade -y
      sudo apt update -y
      sudo apt install qemu qemu-system-x86 linux-image-generic libguestfs-tools sshpass netcat -y
      .gitpod/prepare-rootfs.sh
    command: |
      .gitpod/qemu.sh
