project_name: ns

builds:
  - id: linux-ns
    env:
      - CGO_ENABLED=0
    main: ./cmd/ns
    binary: ns
    flags:
      - -trimpath
    ldflags:
      - -s -w -X namespacelabs.dev/foundation/internal/cli/version.Tag=v{{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: macos-ns
    env:
      - CGO_ENABLED=1
    main: ./cmd/ns
    binary: ns
    flags:
      - -trimpath
    ldflags:
      - -s -w -X namespacelabs.dev/foundation/internal/cli/version.Tag=v{{.Version}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

  - id: linux-nsc
    env:
      - CGO_ENABLED=0
    main: ./cmd/nsc
    binary: nsc
    flags:
      - -trimpath
    ldflags:
      - -s -w -X namespacelabs.dev/foundation/internal/cli/version.Tag=v{{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: macos-nsc
    env:
      - CGO_ENABLED=1
    main: ./cmd/nsc
    binary: nsc
    flags:
      - -trimpath
    ldflags:
      - -s -w -X namespacelabs.dev/foundation/internal/cli/version.Tag=v{{.Version}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: ns
    builds:
      - linux-ns
      - macos-ns
    name_template: "ns_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: nsc
    builds:
      - linux-nsc
      - macos-nsc
    name_template: "nsc_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

# signs:
#   - signature: "${artifact}_macos.dmg"
#     ids:
#       - macos
#     cmd: gon
#     args:
#       - cmd/ns/gon.hcl
#     artifacts: all

release:
  github:
    owner: namespacelabs
    name: foundation
  # extra_files:
  #   - glob: ./dist/fn_macos.dmg
  #   - glob: ./dist/fn_macos.zip

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^nochangelog"
      - "^Merge pull request"
      - "^Merge branch"

brews:
  - tap:
      owner: namespacelabs
      name: homebrew-repo
    name: ns
    ids:
      - ns
    description: "Developer platform with a unified experience from development to production."
    homepage: "https://namespacelabs.com/"
    caveats: |
      Note: ns collects usage telemetry. This data helps us build a better
      platform for you. You can learn more at https://namespace.so/telemetry.

      Check out our examples at https://namespace.so/docs#examples to get started.
    url_template: "https://get.namespace.so/packages/{{.ProjectName}}/v{{.Version}}/{{.ArtifactName}}"
    install: |
      bin.install "ns"
