project_name: nsboot

builds:
  - id: linux
    env:
      - CGO_ENABLED=0
    main: ./cmd/nsboot
    binary: nsboot
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: macos
    env:
      - CGO_ENABLED=1
    main: ./cmd/nsboot
    binary: nsboot
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

release:
  github:
    owner: namespacelabs
    name: foundation
  name_template: "{{.ProjectName}}-v{{.Version}}"

checksum:
  name_template: "checksums.txt"

blobs:
  -
    # Publicly-accessible blobs (mainly to make installation easier while our repos are private).
    provider: s3
    region: us-east-2
    bucket: ns-releases
    folder: "{{ .ProjectName }}/v{{.Version}}"

brews:
  -
    tap:
      owner: namespacelabs
      name: homebrew-repo
    name: ns
    description: "Developer platform with a unified experience from development to production."
    homepage: "https://namespacelabs.com/"
    # Point to the publicly-accessible S3 builds instead of GitHub releases (which are in a private repo).
    url_template: "https://ns-releases.s3.us-east-2.amazonaws.com/{{.ProjectName}}/v{{.Version}}/{{.ArtifactName}}"
    install: |
      libexec.install "nsboot"
      bin.install_symlink libexec/"nsboot" => "ns"
