FROM ubuntu:22.04

RUN apt update
RUN apt install git -y

# Install Node 16
RUN apt install curl -y
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt install nodejs -y

RUN apt clean