// This file is automatically generated.
package s3

#Exports: {
	Bucket: {
		bucketName?: string
		region?:     string

		#Definition: {
			packageName: "namespacelabs.dev/foundation/universe/storage/s3"
			type:        "Bucket"
			typeDefinition: {
				"typename": "foundation.universe.storage.s3.BucketArgs"
				"source": [
					"types.proto",
				]
			}
		}
	}
}
