// This file was automatically generated by Foundation.
// DO NOT EDIT. To update, re-run `fn generate`.

package s3

import (
	"context"
	"namespacelabs.dev/foundation/std/go/core"
	"namespacelabs.dev/foundation/universe/aws/s3"
)

// Dependencies that are instantiated once for the lifetime of the extension.
type ExtensionDeps struct {
	ReadinessCheck core.Check
}

type _checkProvideBucket func(context.Context, *BucketConfig, ExtensionDeps) (*s3.Bucket, error)

var _ _checkProvideBucket = ProvideBucket

var (
	Package__jemnkl = &core.Package{
		PackageName: "namespacelabs.dev/foundation/universe/storage/minio/s3",
	}

	Provider__jemnkl = core.Provider{
		Package:     Package__jemnkl,
		Instantiate: makeDeps__jemnkl,
	}
)

func makeDeps__jemnkl(ctx context.Context, di core.Dependencies) (_ interface{}, err error) {
	var deps ExtensionDeps

	if deps.ReadinessCheck, err = core.ProvideReadinessCheck(ctx, nil); err != nil {
		return nil, err
	}

	return deps, nil
}
