load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "prepare",
    srcs = [
        "cmd.go",
        "eks.go",
        "existing.go",
        "gke.go",
        "local.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/cli/cmd/prepare",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/build/buildkit",
        "//internal/build/registry",
        "//internal/cli/fncobra",
        "//internal/console",
        "//internal/console/renderwait",
        "//internal/executor",
        "//internal/fnerrors",
        "//internal/networking/ingress/nginx",
        "//internal/parsing",
        "//internal/parsing/devhost",
        "//internal/prepare",
        "//internal/protos",
        "//internal/runtime/kubernetes",
        "//internal/runtime/kubernetes/client",
        "//schema",
        "//schema/orchestration",
        "//std/cfg",
        "//std/module",
        "//std/pkggraph",
        "@com_github_google_go_containerregistry//pkg/name",
        "@com_github_spf13_cobra//:cobra",
        "@org_golang_google_protobuf//types/known/anypb",
        "@org_golang_x_exp//slices",
    ],
)
