load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "postgres",
    srcs = [
        "database.pb.go",
        "db.go",
        "deps.fn.go",
        "factory.go",
        "provider.pb.go",
        "resource.go",
        "tx.go",
        "wire.go",
    ],
    importpath = "namespacelabs.dev/foundation/universe/db/postgres",
    visibility = ["//visibility:public"],
    deps = [
        "//framework/resources",
        "//framework/tracing",
        "//internal/fnerrors",
        "//library/database/postgres",
        "//library/oss/postgres",
        "//std/go/core",
        "//std/monitoring/tracing",
        "//std/proto",
        "//std/types",
        "@com_github_cenkalti_backoff_v4//:backoff",
        "@com_github_exaring_otelpgx//:otelpgx",
        "@com_github_jackc_pgerrcode//:pgerrcode",
        "@com_github_jackc_pgx_v5//:pgx",
        "@com_github_jackc_pgx_v5//pgconn",
        "@com_github_jackc_pgx_v5//pgxpool",
        "@com_github_prometheus_client_golang//prometheus",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel//semconv/v1.40.0:v1_40_0",
        "@io_opentelemetry_go_otel_trace//:trace",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//runtime/protoimpl",
        "@org_golang_google_protobuf//types/known/durationpb",
        "@org_golang_x_exp//slices",
    ],
)
