// This file is automatically generated.
package postgres

#Exports: {
	Database: {
		resourceRef?: string

		#Definition: {
			packageName: "namespacelabs.dev/foundation/universe/db/postgres"
			type:        "Database"
			typeDefinition: {
				"typename": "foundation.universe.db.postgres.DatabaseArgs"
				"source": [
					"provider.proto",
				]
			}
		}
	}
}
