// This file was automatically generated by Namespace.
// DO NOT EDIT. To update, re-run `ns generate`.

package counter

import (
	"context"
	"namespacelabs.dev/foundation/internal/testdata/counter/data"
	"namespacelabs.dev/foundation/std/go/core"
)

// Scoped dependencies that are instantiated for each call to ProvideCounter.
type CounterDeps struct {
	Data *data.Data
}

type _checkProvideCounter func(context.Context, *Input, CounterDeps) (*Counter, error)

var _ _checkProvideCounter = ProvideCounter

var (
	Package__mra5r6 = &core.Package{
		PackageName: "namespacelabs.dev/foundation/internal/testdata/counter",
	}

	Provider__mra5r6__Counter = core.Provider{
		Package:     Package__mra5r6,
		Typename:    "Counter",
		Instantiate: makeDeps__mra5r6__Counter,
	}
)

func makeDeps__mra5r6__Counter(ctx context.Context, di core.Dependencies) (_ interface{}, err error) {
	var deps CounterDeps

	if deps.Data, err = data.ProvideData(ctx, nil); err != nil {
		return nil, err
	}

	return deps, nil
}
