load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "runtime",
    srcs = [
        "fillresolvable.go",
        "ingress.go",
        "injections.go",
        "interface.go",
        "naming.go",
        "prepare.go",
        "registry.go",
        "runattached.go",
        "selector.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/runtime",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/console/termios",
        "//framework/kubernetes/kubenaming",
        "//framework/resources",
        "//framework/secrets",
        "//internal/artifacts/oci",
        "//internal/artifacts/registry",
        "//internal/console",
        "//internal/executor",
        "//internal/fnerrors",
        "//internal/planning/constants",
        "//internal/protos",
        "//internal/runtime/rtypes",
        "//internal/uniquestrings",
        "//schema",
        "//schema/runtime",
        "//schema/storage",
        "//std/cfg",
        "//std/execution",
        "//std/resources",
        "@com_github_opencontainers_image_spec//specs-go/v1:specs-go",
        "@com_github_tailscale_hujson//:hujson",
        "@org_golang_google_protobuf//types/known/anypb",
    ],
)
