load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "fncobra",
    srcs = [
        "do.go",
        "envbound.go",
        "flags.go",
        "install.go",
        "locbound.go",
        "main.go",
        "notsupported.go",
        "notsupported_other.go",
        "notsupported_windows.go",
        "pprof.go",
        "sigint.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/cli/fncobra",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/console/termios",
        "//framework/ulimit",
        "//internal/clerk",
        "//internal/cli/fncobra/name",
        "//internal/cli/nsboot",
        "//internal/cli/version",
        "//internal/cli/versioncheck",
        "//internal/compute",
        "//internal/console",
        "//internal/console/colors",
        "//internal/console/consolesink",
        "//internal/duration",
        "//internal/environment",
        "//internal/fnapi",
        "//internal/fnerrors",
        "//internal/fnerrors/format",
        "//internal/fnfs",
        "//internal/fnfs/fsdigest",
        "//internal/fnnet",
        "//internal/parsing",
        "//internal/storedrun",
        "//internal/welcome",
        "//internal/workspace/dirs",
        "//schema",
        "//std/cfg",
        "//std/cfg/knobs",
        "//std/module",
        "//std/tasks",
        "//std/tasks/actiontracing",
        "//std/tasks/idtypes",
        "//std/tasks/simplelog",
        "//universe/vault",
        "@com_github_containerd_log//:log",
        "@com_github_google_go_containerregistry//pkg/logs",
        "@com_github_gorilla_mux//:mux",
        "@com_github_sirupsen_logrus//:logrus",
        "@com_github_spf13_cobra//:cobra",
        "@com_github_spf13_pflag//:pflag",
        "@com_github_spf13_viper//:viper",
        "@org_uber_go_atomic//:atomic",
    ],
)
