// This file was automatically generated by Namespace.
// DO NOT EDIT. To update, re-run `ns generate`.

package service

import (
	"context"
	"namespacelabs.dev/foundation/std/go/core"
	"namespacelabs.dev/foundation/std/go/server"
)

// Dependencies that are instantiated once for the lifetime of the service.
type ServiceDeps struct {
}

// Verify that WireService is present and has the appropriate type.
type checkWireService func(context.Context, server.Registrar, ServiceDeps)

var _ checkWireService = WireService

var (
	Package__v9aee7 = &core.Package{
		PackageName: "namespacelabs.dev/foundation/orchestration/service",
	}

	Provider__v9aee7 = core.Provider{
		Package:     Package__v9aee7,
		Instantiate: makeDeps__v9aee7,
	}
)

func makeDeps__v9aee7(ctx context.Context, di core.Dependencies) (_ interface{}, err error) {
	var deps ServiceDeps

	return deps, nil
}
