load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "golang",
    srcs = [
        "baseimage.go",
        "bazel.go",
        "buildkit.go",
        "dependency.go",
        "generate.pb.go",
        "gennode.go",
        "genserver.go",
        "gobinary.go",
        "gobuild.go",
        "golang.go",
        "localbuild.go",
        "op.pb.go",
        "src.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/integrations/golang",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/findroot",
        "//framework/kubernetes/kubenaming",
        "//internal/artifacts/oci",
        "//internal/build",
        "//internal/build/assets",
        "//internal/build/baseimage",
        "//internal/build/buildkit",
        "//internal/codegen",
        "//internal/codegen/protos",
        "//internal/compute",
        "//internal/console",
        "//internal/dependencies/pins",
        "//internal/fnerrors",
        "//internal/fnfs",
        "//internal/fnfs/memfs",
        "//internal/git",
        "//internal/gosupport",
        "//internal/integrations",
        "//internal/integrations/golang/rungo",
        "//internal/integrations/shared",
        "//internal/llbutil",
        "//internal/localexec",
        "//internal/parsing",
        "//internal/parsing/platform",
        "//internal/planning",
        "//internal/production",
        "//internal/runtime",
        "//internal/sdk/golang",
        "//internal/sdk/host",
        "//internal/workspace/dirs",
        "//schema",
        "//std/cfg",
        "//std/cfg/knobs",
        "//std/execution",
        "//std/execution/defs",
        "//std/pkggraph",
        "//std/tasks",
        "@com_github_bazelbuild_bazelisk//core",
        "@com_github_bazelbuild_bazelisk//repositories",
        "@com_github_kr_text//:text",
        "@com_github_moby_buildkit//client/llb",
        "@com_github_moby_buildkit//util/system",
        "@com_github_opencontainers_image_spec//specs-go/v1:specs-go",
        "@com_github_protocolbuffers_txtpbfmt//parser",
        "@io_k8s_utils//ptr",
        "@org_golang_google_protobuf//encoding/prototext",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//runtime/protoimpl",
        "@org_golang_google_protobuf//types/dynamicpb",
        "@org_golang_google_protobuf//types/known/anypb",
        "@org_golang_x_exp//maps",
        "@org_golang_x_exp//slices",
        "@org_golang_x_mod//semver",
    ],
)
