load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "secrets",
    srcs = [
        "addreader.go",
        "cmd.go",
        "delete.go",
        "info.go",
        "reveal.go",
        "set.go",
        "setreaders.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/cli/cmd/secrets",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/secrets/localsecrets",
        "//internal/cli/fncobra",
        "//internal/console",
        "//internal/console/tui",
        "//internal/fnerrors",
        "//internal/fnfs",
        "//internal/keys",
        "//internal/parsing",
        "//schema",
        "//std/cfg",
        "@com_github_charmbracelet_lipgloss//:lipgloss",
        "@com_github_kr_text//:text",
        "@com_github_spf13_cobra//:cobra",
        "@io_k8s_utils//ptr",
    ],
)
