load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "debug",
    srcs = [
        "actiondemo.go",
        "cmd.go",
        "config.go",
        "decodeproto.go",
        "dnsquery.go",
        "download.go",
        "findconfig.go",
        "fnservices.go",
        "image.go",
        "imageindex.go",
        "inlinespec.go",
        "kubernetes.go",
        "prepare.go",
        "printcomputed.go",
        "printsealed.go",
        "updatelicense.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/cli/cmd/debug",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/networking/dns",
        "//internal/artifacts",
        "//internal/artifacts/download",
        "//internal/artifacts/oci",
        "//internal/bytestream",
        "//internal/cli/fncobra",
        "//internal/cli/fncobra/planningargs",
        "//internal/codegen/protos/resolver",
        "//internal/compute",
        "//internal/console",
        "//internal/fnapi",
        "//internal/fnerrors",
        "//internal/fnfs",
        "//internal/parsing",
        "//internal/planning",
        "//internal/planning/deploy",
        "//internal/providers/nscloud/metadata",
        "//internal/runtime",
        "//internal/runtime/docker/install",
        "//internal/runtime/kubernetes",
        "//internal/workspace/dirs",
        "//schema",
        "//std/cfg",
        "//std/module",
        "//std/pkggraph",
        "//std/tasks",
        "@com_github_andybalholm_brotli//:brotli",
        "@com_github_dustin_go_humanize//:go-humanize",
        "@com_github_google_go_containerregistry//pkg/v1:pkg",
        "@com_github_google_go_containerregistry//pkg/v1/daemon",
        "@com_github_google_go_containerregistry//pkg/v1/remote",
        "@com_github_spf13_cobra//:cobra",
        "@com_github_spf13_pflag//:pflag",
        "@io_k8s_api//apps/v1:apps",
        "@io_k8s_api//batch/v1:batch",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_api//networking/v1:networking",
        "@io_k8s_api//rbac/v1:rbac",
        "@io_k8s_apiextensions_apiserver//pkg/apis/apiextensions/v1:apiextensions",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/apis/meta/v1/unstructured",
        "@io_k8s_apimachinery//pkg/runtime",
        "@io_k8s_apimachinery//pkg/runtime/schema",
        "@io_k8s_apimachinery//pkg/runtime/serializer",
        "@io_k8s_apimachinery//pkg/watch",
        "@io_k8s_client_go//rest",
        "@org_golang_google_protobuf//encoding/protojson",
        "@org_golang_google_protobuf//encoding/prototext",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//reflect/protoregistry",
        "@org_golang_x_exp//slices",
        "@org_golang_x_sync//errgroup",
    ],
)
