load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "localsecrets",
    srcs = [
        "bundle.go",
        "bundle.pb.go",
        "localsecrets.go",
    ],
    importpath = "namespacelabs.dev/foundation/framework/secrets/localsecrets",
    visibility = ["//visibility:public"],
    deps = [
        "//framework/secrets",
        "//internal/fnerrors",
        "//internal/fnfs",
        "//internal/fnfs/maketarfs",
        "//internal/fnfs/memfs",
        "//internal/fnfs/tarfs",
        "//internal/keys",
        "//schema",
        "//std/cfg",
        "//std/pkggraph",
        "@com_github_muesli_reflow//wordwrap",
        "@io_filippo_age//:age",
        "@org_golang_google_protobuf//encoding/protojson",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//runtime/protoimpl",
        "@org_golang_x_exp//slices",
    ],
)
