// This file was automatically generated by Foundation.
// DO NOT EDIT. To update, re-run `fn generate`.

package main

import (
	"context"
	"namespacelabs.dev/foundation/std/go/core"
	"namespacelabs.dev/foundation/std/go/grpc/metrics"
	"namespacelabs.dev/foundation/std/go/server"
	"namespacelabs.dev/foundation/std/monitoring/tracing"
	"namespacelabs.dev/foundation/std/testdata/service/list"
	"namespacelabs.dev/foundation/std/testdata/service/proto"
)

func RegisterInitializers(di *core.DependencyGraph) {
	di.AddInitializers(metrics.Initializers__so2f3v...)
	di.AddInitializers(tracing.Initializers__70o2mm...)
}

func WireServices(ctx context.Context, srv server.Server, depgraph core.Dependencies) []error {
	var errs []error

	if err := depgraph.Instantiate(ctx, list.Provider__ffkppv, func(ctx context.Context, v interface{}) error {
		list.WireService(ctx, srv.Scope(list.Package__ffkppv), v.(list.ServiceDeps))
		return nil
	}); err != nil {
		errs = append(errs, err)
	}

	srv.InternalRegisterGrpcGateway(proto.RegisterListServiceHandler)

	return errs
}
