load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "rungo",
    srcs = [
        "env.go",
        "rungo.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/integrations/golang/rungo",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/git",
        "//internal/localexec",
        "//internal/sdk/golang",
        "//std/pkggraph",
        "//std/tasks",
    ],
)
