// Copyright 2022 Namespace Labs Inc; All rights reserved.
// Licensed under the EARLY ACCESS SOFTWARE LICENSE AGREEMENT
// available at http://github.com/namespacelabs/foundation

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: std/types/invocation.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "namespacelabs.dev/foundation/std/proto"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeferredInvocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Binary string `protobuf:"bytes,1,opt,name=binary,proto3" json:"binary,omitempty"`
}

func (x *DeferredInvocation) Reset() {
	*x = DeferredInvocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_std_types_invocation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeferredInvocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeferredInvocation) ProtoMessage() {}

func (x *DeferredInvocation) ProtoReflect() protoreflect.Message {
	mi := &file_std_types_invocation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeferredInvocation.ProtoReflect.Descriptor instead.
func (*DeferredInvocation) Descriptor() ([]byte, []int) {
	return file_std_types_invocation_proto_rawDescGZIP(), []int{0}
}

func (x *DeferredInvocation) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

var File_std_types_invocation_proto protoreflect.FileDescriptor

var file_std_types_invocation_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x74, 0x64, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x69, 0x6e, 0x76, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x66, 0x6f,
	0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x73, 0x74, 0x64, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x1a, 0x17, 0x73, 0x74, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x12, 0x44,
	0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x49, 0x6e, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1c, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x04, 0x80, 0xa6, 0x1d, 0x01, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x42,
	0x28, 0x5a, 0x26, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6c, 0x61, 0x62, 0x73,
	0x2e, 0x64, 0x65, 0x76, 0x2f, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x73, 0x74, 0x64, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_std_types_invocation_proto_rawDescOnce sync.Once
	file_std_types_invocation_proto_rawDescData = file_std_types_invocation_proto_rawDesc
)

func file_std_types_invocation_proto_rawDescGZIP() []byte {
	file_std_types_invocation_proto_rawDescOnce.Do(func() {
		file_std_types_invocation_proto_rawDescData = protoimpl.X.CompressGZIP(file_std_types_invocation_proto_rawDescData)
	})
	return file_std_types_invocation_proto_rawDescData
}

var file_std_types_invocation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_std_types_invocation_proto_goTypes = []interface{}{
	(*DeferredInvocation)(nil), // 0: foundation.std.types.DeferredInvocation
}
var file_std_types_invocation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_std_types_invocation_proto_init() }
func file_std_types_invocation_proto_init() {
	if File_std_types_invocation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_std_types_invocation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeferredInvocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_std_types_invocation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_std_types_invocation_proto_goTypes,
		DependencyIndexes: file_std_types_invocation_proto_depIdxs,
		MessageInfos:      file_std_types_invocation_proto_msgTypes,
	}.Build()
	File_std_types_invocation_proto = out.File
	file_std_types_invocation_proto_rawDesc = nil
	file_std_types_invocation_proto_goTypes = nil
	file_std_types_invocation_proto_depIdxs = nil
}
