// This file was automatically generated by Namespace.
// DO NOT EDIT. To update, re-run `ns generate`.

package simplewithconfiguration

import (
	"context"
	"namespacelabs.dev/foundation/std/go/core"
	"namespacelabs.dev/foundation/std/go/server"
)

// Dependencies that are instantiated once for the lifetime of the service.
type ServiceDeps struct {
}

// Verify that WireService is present and has the appropriate type.
type checkWireService func(context.Context, server.Registrar, ServiceDeps)

var _ checkWireService = WireService

var (
	Package__luc6um = &core.Package{
		PackageName:       "namespacelabs.dev/foundation/internal/testdata/service/simplewithconfiguration",
		ConfigurationName: "mtls",
	}

	Provider__luc6um = core.Provider{
		Package:     Package__luc6um,
		Instantiate: makeDeps__luc6um,
	}
)

func makeDeps__luc6um(ctx context.Context, di core.Dependencies) (_ interface{}, err error) {
	var deps ServiceDeps

	return deps, nil
}
