load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "secrets",
    srcs = [
        "nosecrets.go",
        "secrets.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/planning/secrets",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/rpcerrors/multierr",
        "//framework/secrets",
        "//internal/fnerrors",
        "//schema",
        "//std/pkggraph",
    ],
)
