// This file is automatically generated.
package creds

#Exports: {
	Creds: {
		#Definition: {
			packageName: "namespacelabs.dev/foundation/universe/storage/minio/creds"
			type:        "Creds"
			typeDefinition: {
				"typename": "foundation.universe.storage.minio.creds.CredsRequest"
				"source": [
					"provider.proto",
				]
			}
		}
	}
}
