load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "csrf",
    srcs = [
        "deps.fn.go",
        "wire.go",
    ],
    importpath = "namespacelabs.dev/foundation/std/go/http/csrf",
    visibility = ["//visibility:public"],
    deps = [
        "//framework/resources",
        "//std/go/core",
        "@com_github_gorilla_csrf//:csrf",
        "@com_github_gorilla_mux//:mux",
    ],
)
