load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "prepare",
    srcs = [
        "aws.go",
        "buildcluster.go",
        "eks.go",
        "gcp.go",
        "gke.go",
        "ingress.go",
        "k3d.go",
        "k8s.go",
        "kubernetes.go",
        "nscloud.go",
        "orchestrator.go",
        "types.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/prepare",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/build/buildkit",
        "//framework/kubernetes/kubedef",
        "//framework/rpcerrors/multierr",
        "//internal/build/registry",
        "//internal/executor",
        "//internal/fnerrors",
        "//internal/parsing/devhost",
        "//internal/planning/deploy",
        "//internal/providers/k3d",
        "//internal/providers/nscloud/api",
        "//internal/providers/nscloud/api/private",
        "//internal/providers/nscloud/nsingress",
        "//internal/runtime",
        "//internal/runtime/docker",
        "//internal/runtime/kubernetes",
        "//internal/runtime/kubernetes/client",
        "//internal/sdk/host",
        "//internal/sdk/k3d",
        "//orchestration",
        "//schema",
        "//schema/orchestration",
        "//std/cfg",
        "//std/execution",
        "//std/execution/defs",
        "//std/tasks",
        "//universe/aws/configuration",
        "//universe/aws/configuration/eks",
        "//universe/gcp",
        "//universe/gcp/gke",
        "//universe/nscloud/configuration",
        "@com_github_containerd_errdefs//:errdefs",
        "@com_github_moby_moby_api//types/container",
        "@com_github_moby_moby_api//types/network",
        "@com_github_moby_moby_client//:client",
        "@io_k8s_api//core/v1:core",
        "@org_golang_google_protobuf//proto",
    ],
)
