load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "cuefrontend",
    srcs = [
        "applyinputs.go",
        "binary.go",
        "evalstate.go",
        "fetchers.go",
        "fieldvalidator.go",
        "framework.go",
        "frontend.go",
        "module.go",
        "mounts.go",
        "naming.go",
        "node.go",
        "package.go",
        "phase0.go",
        "phase1.go",
        "phase2.go",
        "resourceclass.go",
        "resourceprovider.go",
        "resources.go",
        "secrets.go",
        "server.go",
        "testoldsyntax.go",
        "tests.go",
        "volumes.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/frontend/cuefrontend",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/jsonreparser",
        "//framework/rpcerrors/multierr",
        "//internal/bytestream",
        "//internal/codegen/protos",
        "//internal/codegen/protos/fnany",
        "//internal/fnerrors",
        "//internal/fnfs",
        "//internal/fnfs/memfs",
        "//internal/frontend/cuefrontend/args",
        "//internal/frontend/cuefrontend/binary",
        "//internal/frontend/cuefrontend/integration/api",
        "//internal/frontend/fncue",
        "//internal/hotreload/constants",
        "//internal/parsing",
        "//internal/parsing/invariants",
        "//internal/protos",
        "//internal/uniquestrings",
        "//internal/versions",
        "//internal/workspace",
        "//schema",
        "//std/pkggraph",
        "//std/runtime/constants",
        "//std/tasks",
        "//std/types",
        "@com_github_agext_levenshtein//:levenshtein",
        "@com_github_docker_go_units//:go-units",
        "@io_k8s_utils//strings/slices",
        "@org_cuelang_go//cue",
        "@org_cuelang_go//cue/ast",
        "@org_cuelang_go//cue/cuecontext",
        "@org_cuelang_go//cue/format",
        "@org_golang_google_protobuf//encoding/protojson",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//reflect/protoregistry",
        "@org_golang_google_protobuf//types/descriptorpb",
        "@org_golang_google_protobuf//types/dynamicpb",
        "@org_golang_google_protobuf//types/known/anypb",
        "@org_golang_x_exp//maps",
        "@org_golang_x_exp//slices",
    ],
)
