load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "servercore",
    srcs = [
        "cloudflare.go",
        "configurations.go",
        "entrypoint.go",
        "interceptors.go",
        "listener.go",
        "mtls.go",
        "registrar.go",
        "sigterm.go",
        "transporttracing.go",
    ],
    importpath = "namespacelabs.dev/foundation/std/go/grpc/servercore",
    visibility = ["//visibility:public"],
    deps = [
        "//framework/runtime",
        "//internal/fnerrors",
        "//schema",
        "//schema/runtime",
        "//std/go/core",
        "//std/go/grpc",
        "//std/go/grpc/interceptors",
        "//std/go/http/middleware",
        "//std/grpc/requestid",
        "@com_github_gorilla_mux//:mux",
        "@com_github_grpc_ecosystem_go_grpc_middleware//:go-grpc-middleware",
        "@com_github_grpc_ecosystem_go_grpc_prometheus//:go-grpc-prometheus",
        "@com_github_philopon_go_toposort//:go-toposort",
        "@com_github_prometheus_client_golang//prometheus",
        "@com_github_rs_zerolog//hlog",
        "@com_github_soheilhy_cmux//:cmux",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel_trace//:trace",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials",
        "@org_golang_google_grpc//health",
        "@org_golang_google_grpc//health/grpc_health_v1",
        "@org_golang_google_grpc//keepalive",
        "@org_golang_google_grpc//peer",
        "@org_golang_google_grpc//reflection",
        "@org_golang_x_net//http2",
        "@org_golang_x_net//http2/h2c",
        "@org_golang_x_sync//errgroup",
        "@org_uber_go_automaxprocs//maxprocs",
    ],
)
