load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "kubernetes",
    srcs = [
        "cluster.go",
        "clusternamespace.go",
        "delete.go",
        "deployment.go",
        "diagnostics.go",
        "environment.go",
        "fillenv.go",
        "hooks.go",
        "ingress.go",
        "logs.go",
        "naming.go",
        "oneshot.go",
        "planner.go",
        "platforms.go",
        "portforward.go",
        "probes.go",
        "resolvepod.go",
        "runtime.go",
        "secrets.go",
        "securitycontext.go",
        "systeminfo.go",
        "terminal.go",
        "volumes.go",
    ],
    embedsrcs = [
        "defaults/container.securitycontext.yaml",
        "defaults/pod.podsecuritycontext.yaml",
    ],
    importpath = "namespacelabs.dev/foundation/internal/runtime/kubernetes",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/console/termios",
        "//framework/kubernetes/kubedef",
        "//framework/kubernetes/kubenaming",
        "//framework/kubernetes/kubeobj",
        "//framework/kubernetes/kubetool",
        "//framework/rpcerrors/multierr",
        "//framework/secrets",
        "//internal/artifacts/oci",
        "//internal/artifacts/registry",
        "//internal/compute",
        "//internal/console",
        "//internal/executor",
        "//internal/fnerrors",
        "//internal/fnnet",
        "//internal/networking/ingress",
        "//internal/parsing/platform",
        "//internal/planning/constants",
        "//internal/planning/planninghooks",
        "//internal/protos",
        "//internal/runtime",
        "//internal/runtime/kubernetes/client",
        "//internal/runtime/kubernetes/kubeobserver",
        "//internal/runtime/kubernetes/readiness",
        "//internal/runtime/rtypes",
        "//internal/secrets",
        "//internal/support",
        "//internal/tcache",
        "//internal/uniquestrings",
        "//library/kubernetes/rbac",
        "//orchestration/client",
        "//schema",
        "//schema/allocations",
        "//schema/runtime",
        "//schema/storage",
        "//std/cfg",
        "//std/execution/defs",
        "//std/resources",
        "//std/runtime/constants",
        "//std/runtime/kubernetes",
        "//std/tasks",
        "//std/tasks/idtypes",
        "@com_github_dustin_go_humanize//:go-humanize",
        "@com_github_opencontainers_image_spec//specs-go/v1:specs-go",
        "@dev_namespacelabs_go_ids//:go-ids",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_apimachinery//pkg/api/errors",
        "@io_k8s_apimachinery//pkg/api/resource",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/runtime",
        "@io_k8s_apimachinery//pkg/runtime/schema",
        "@io_k8s_apimachinery//pkg/util/httpstream",
        "@io_k8s_apimachinery//pkg/util/intstr",
        "@io_k8s_apimachinery//pkg/watch",
        "@io_k8s_client_go//applyconfigurations/apps/v1:apps",
        "@io_k8s_client_go//applyconfigurations/core/v1:core",
        "@io_k8s_client_go//applyconfigurations/meta/v1:meta",
        "@io_k8s_client_go//applyconfigurations/rbac/v1:rbac",
        "@io_k8s_client_go//discovery",
        "@io_k8s_client_go//kubernetes",
        "@io_k8s_client_go//kubernetes/scheme",
        "@io_k8s_client_go//rest",
        "@io_k8s_client_go//restmapper",
        "@io_k8s_client_go//tools/remotecommand",
        "@io_k8s_client_go//transport/spdy",
        "@io_k8s_sigs_yaml//:yaml",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//types/known/anypb",
        "@org_golang_x_exp//slices",
    ],
)
