// Copyright 2022 Namespace Labs Inc; All rights reserved.
// Licensed under the EARLY ACCESS SOFTWARE LICENSE AGREEMENT
// available at http://github.com/namespacelabs/foundation

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: provision/deploy/render/ui.proto

package render

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkPlanSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocalHostname   string                        `protobuf:"bytes,1,opt,name=local_hostname,json=localHostname,proto3" json:"local_hostname,omitempty"`
	FocusedServices []*NetworkPlanSummary_Service `protobuf:"bytes,2,rep,name=focused_services,json=focusedServices,proto3" json:"focused_services,omitempty"`
	SupportServices []*NetworkPlanSummary_Service `protobuf:"bytes,3,rep,name=support_services,json=supportServices,proto3" json:"support_services,omitempty"`
}

func (x *NetworkPlanSummary) Reset() {
	*x = NetworkPlanSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_provision_deploy_render_ui_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkPlanSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPlanSummary) ProtoMessage() {}

func (x *NetworkPlanSummary) ProtoReflect() protoreflect.Message {
	mi := &file_provision_deploy_render_ui_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPlanSummary.ProtoReflect.Descriptor instead.
func (*NetworkPlanSummary) Descriptor() ([]byte, []int) {
	return file_provision_deploy_render_ui_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkPlanSummary) GetLocalHostname() string {
	if x != nil {
		return x.LocalHostname
	}
	return ""
}

func (x *NetworkPlanSummary) GetFocusedServices() []*NetworkPlanSummary_Service {
	if x != nil {
		return x.FocusedServices
	}
	return nil
}

func (x *NetworkPlanSummary) GetSupportServices() []*NetworkPlanSummary_Service {
	if x != nil {
		return x.SupportServices
	}
	return nil
}

type Label struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label        string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	ServiceProto string `protobuf:"bytes,2,opt,name=service_proto,json=serviceProto,proto3" json:"service_proto,omitempty"`
}

func (x *Label) Reset() {
	*x = Label{}
	if protoimpl.UnsafeEnabled {
		mi := &file_provision_deploy_render_ui_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_provision_deploy_render_ui_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_provision_deploy_render_ui_proto_rawDescGZIP(), []int{1}
}

func (x *Label) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Label) GetServiceProto() string {
	if x != nil {
		return x.ServiceProto
	}
	return ""
}

type NetworkPlanSummary_Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label       *Label `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Focus       bool   `protobuf:"varint,2,opt,name=focus,proto3" json:"focus,omitempty"`
	LocalPort   uint32 `protobuf:"varint,4,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	PackageName string `protobuf:"bytes,5,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	// Guaranteed to be non-empty.
	AccessCmd []*NetworkPlanSummary_Service_AccessCmd `protobuf:"bytes,6,rep,name=access_cmd,json=accessCmd,proto3" json:"access_cmd,omitempty"`
}

func (x *NetworkPlanSummary_Service) Reset() {
	*x = NetworkPlanSummary_Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_provision_deploy_render_ui_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkPlanSummary_Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPlanSummary_Service) ProtoMessage() {}

func (x *NetworkPlanSummary_Service) ProtoReflect() protoreflect.Message {
	mi := &file_provision_deploy_render_ui_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPlanSummary_Service.ProtoReflect.Descriptor instead.
func (*NetworkPlanSummary_Service) Descriptor() ([]byte, []int) {
	return file_provision_deploy_render_ui_proto_rawDescGZIP(), []int{0, 0}
}

func (x *NetworkPlanSummary_Service) GetLabel() *Label {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *NetworkPlanSummary_Service) GetFocus() bool {
	if x != nil {
		return x.Focus
	}
	return false
}

func (x *NetworkPlanSummary_Service) GetLocalPort() uint32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *NetworkPlanSummary_Service) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *NetworkPlanSummary_Service) GetAccessCmd() []*NetworkPlanSummary_Service_AccessCmd {
	if x != nil {
		return x.AccessCmd
	}
	return nil
}

type NetworkPlanSummary_Service_AccessCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// url for http
	// "grpcurl" command line for grpc
	// "curl" command line for http transcoding.
	// "private:" if the service can't be accessed from outside.
	Cmd string `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	// Whether it is managed by Namespace.
	IsManaged bool `protobuf:"varint,2,opt,name=is_managed,json=isManaged,proto3" json:"is_managed,omitempty"`
}

func (x *NetworkPlanSummary_Service_AccessCmd) Reset() {
	*x = NetworkPlanSummary_Service_AccessCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_provision_deploy_render_ui_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkPlanSummary_Service_AccessCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPlanSummary_Service_AccessCmd) ProtoMessage() {}

func (x *NetworkPlanSummary_Service_AccessCmd) ProtoReflect() protoreflect.Message {
	mi := &file_provision_deploy_render_ui_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPlanSummary_Service_AccessCmd.ProtoReflect.Descriptor instead.
func (*NetworkPlanSummary_Service_AccessCmd) Descriptor() ([]byte, []int) {
	return file_provision_deploy_render_ui_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *NetworkPlanSummary_Service_AccessCmd) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *NetworkPlanSummary_Service_AccessCmd) GetIsManaged() bool {
	if x != nil {
		return x.IsManaged
	}
	return false
}

var File_provision_deploy_render_ui_proto protoreflect.FileDescriptor

var file_provision_deploy_render_ui_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x64, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x2f, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x75, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x17, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x64, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x2e, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0xb1, 0x04, 0x0a, 0x12,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x6c, 0x61, 0x6e, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x68, 0x6f, 0x73, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x5e, 0x0a, 0x10, 0x66, 0x6f, 0x63,
	0x75, 0x73, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e,
	0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2e, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x6c, 0x61, 0x6e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x0f, 0x66, 0x6f, 0x63, 0x75, 0x73, 0x65,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x5e, 0x0a, 0x10, 0x73, 0x75, 0x70,
	0x70, 0x6f, 0x72, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e,
	0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2e, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x6c, 0x61, 0x6e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x0f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x1a, 0xb3, 0x02, 0x0a, 0x07, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x2e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2e, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x66,
	0x6f, 0x63, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x63, 0x75,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x6f, 0x72, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x5c, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x63, 0x6d,
	0x64, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3d, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x2e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2e, 0x72, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x6c, 0x61, 0x6e, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x43, 0x6d, 0x64, 0x52, 0x09, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6d,
	0x64, 0x1a, 0x3c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6d, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x22,
	0x42, 0x0a, 0x05, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x23,
	0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x42, 0x2b, 0x5a, 0x29, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x6c, 0x61, 0x62, 0x73, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2f, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_provision_deploy_render_ui_proto_rawDescOnce sync.Once
	file_provision_deploy_render_ui_proto_rawDescData = file_provision_deploy_render_ui_proto_rawDesc
)

func file_provision_deploy_render_ui_proto_rawDescGZIP() []byte {
	file_provision_deploy_render_ui_proto_rawDescOnce.Do(func() {
		file_provision_deploy_render_ui_proto_rawDescData = protoimpl.X.CompressGZIP(file_provision_deploy_render_ui_proto_rawDescData)
	})
	return file_provision_deploy_render_ui_proto_rawDescData
}

var file_provision_deploy_render_ui_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_provision_deploy_render_ui_proto_goTypes = []interface{}{
	(*NetworkPlanSummary)(nil),                   // 0: provision.deploy.render.NetworkPlanSummary
	(*Label)(nil),                                // 1: provision.deploy.render.Label
	(*NetworkPlanSummary_Service)(nil),           // 2: provision.deploy.render.NetworkPlanSummary.Service
	(*NetworkPlanSummary_Service_AccessCmd)(nil), // 3: provision.deploy.render.NetworkPlanSummary.Service.AccessCmd
}
var file_provision_deploy_render_ui_proto_depIdxs = []int32{
	2, // 0: provision.deploy.render.NetworkPlanSummary.focused_services:type_name -> provision.deploy.render.NetworkPlanSummary.Service
	2, // 1: provision.deploy.render.NetworkPlanSummary.support_services:type_name -> provision.deploy.render.NetworkPlanSummary.Service
	1, // 2: provision.deploy.render.NetworkPlanSummary.Service.label:type_name -> provision.deploy.render.Label
	3, // 3: provision.deploy.render.NetworkPlanSummary.Service.access_cmd:type_name -> provision.deploy.render.NetworkPlanSummary.Service.AccessCmd
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_provision_deploy_render_ui_proto_init() }
func file_provision_deploy_render_ui_proto_init() {
	if File_provision_deploy_render_ui_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_provision_deploy_render_ui_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkPlanSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_provision_deploy_render_ui_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Label); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_provision_deploy_render_ui_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkPlanSummary_Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_provision_deploy_render_ui_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkPlanSummary_Service_AccessCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_provision_deploy_render_ui_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_provision_deploy_render_ui_proto_goTypes,
		DependencyIndexes: file_provision_deploy_render_ui_proto_depIdxs,
		MessageInfos:      file_provision_deploy_render_ui_proto_msgTypes,
	}.Build()
	File_provision_deploy_render_ui_proto = out.File
	file_provision_deploy_render_ui_proto_rawDesc = nil
	file_provision_deploy_render_ui_proto_goTypes = nil
	file_provision_deploy_render_ui_proto_depIdxs = nil
}
