load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "rtypes",
    srcs = [
        "provision.go",
        "rtypes.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/runtime/rtypes",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/artifacts/oci",
        "//internal/console",
        "//schema",
        "@org_golang_google_protobuf//proto",
    ],
)
