load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "planning",
    srcs = [
        "builder.go",
        "endpoints.go",
        "planner.go",
        "resources.go",
        "server.go",
        "stack.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/planning",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/rpcerrors/multierr",
        "//framework/secrets",
        "//framework/secrets/combined",
        "//internal/artifacts/oci",
        "//internal/artifacts/registry",
        "//internal/build/buildkit",
        "//internal/compute",
        "//internal/console",
        "//internal/executor",
        "//internal/fnerrors",
        "//internal/parsing",
        "//internal/planning/compatibility",
        "//internal/planning/constants",
        "//internal/planning/eval",
        "//internal/planning/invocation",
        "//internal/planning/planninghooks",
        "//internal/planning/secrets",
        "//internal/planning/tool",
        "//internal/planning/tool/protocol",
        "//internal/protos",
        "//internal/runtime",
        "//internal/runtime/rtypes",
        "//internal/runtime/tools",
        "//internal/support",
        "//internal/versions",
        "//library/kubernetes/ingress",
        "//schema",
        "//std/cfg",
        "//std/pkggraph",
        "//std/resources",
        "//std/runtime/constants",
        "//std/tasks",
        "@org_golang_google_protobuf//types/known/anypb",
        "@org_golang_x_exp//maps",
        "@org_golang_x_exp//slices",
    ],
)
