// This file was automatically generated by Namespace.
// DO NOT EDIT. To update, re-run `ns generate`.

package main

import (
	"context"
	"namespacelabs.dev/foundation/internal/orchestration/service"
	"namespacelabs.dev/foundation/std/go/core"
	"namespacelabs.dev/foundation/std/go/grpc/metrics"
	"namespacelabs.dev/foundation/std/go/server"
)

func RegisterInitializers(di *core.DependencyGraph) {
	di.AddInitializers(metrics.Initializers__so2f3v...)
}

func WireServices(ctx context.Context, srv server.Server, depgraph core.Dependencies) []error {
	var errs []error

	if err := depgraph.Instantiate(ctx, service.Provider__k1rd1l, func(ctx context.Context, v interface{}) error {
		service.WireService(ctx, srv.Scope(service.Package__k1rd1l), v.(service.ServiceDeps))
		return nil
	}); err != nil {
		errs = append(errs, err)
	}

	return errs
}
