load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "testing",
    srcs = [
        "environment.go",
        "fixture.go",
        "prepare.go",
        "request.go",
        "run.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/testing",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/kubernetes/kubenaming",
        "//internal/artifacts/oci",
        "//internal/build",
        "//internal/build/assets",
        "//internal/build/binary",
        "//internal/build/multiplatform",
        "//internal/build/registry",
        "//internal/compute",
        "//internal/console",
        "//internal/executor",
        "//internal/fnerrors",
        "//internal/fnfs/memfs",
        "//internal/parsing",
        "//internal/parsing/platform",
        "//internal/planning",
        "//internal/planning/deploy",
        "//internal/planning/eval",
        "//internal/protos",
        "//internal/runtime",
        "//internal/runtime/kubernetes/client",
        "//internal/support",
        "//internal/sync",
        "//internal/testing/testboot",
        "//orchestration",
        "//schema",
        "//schema/runtime",
        "//schema/storage",
        "//std/cfg",
        "//std/pkggraph",
        "//std/runtime/constants",
        "//std/tasks",
        "//std/tasks/idtypes",
        "@com_github_morikuni_aec//:aec",
        "@dev_namespacelabs_go_ids//:go-ids",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//types/known/anypb",
        "@org_golang_google_protobuf//types/known/timestamppb",
    ],
)
