// This file was automatically generated by Foundation.
// DO NOT EDIT. To update, re-run `fn generate`.

package grpc

import (
	"context"
	"google.golang.org/grpc"
	"namespacelabs.dev/foundation/std/go/core"
)

type _checkProvideConn func(context.Context, *Backend) (*grpc.ClientConn, error)

var _ _checkProvideConn = ProvideConn

var (
	Package__k4hdjh = &core.Package{
		PackageName: "namespacelabs.dev/foundation/std/grpc",
	}
)
