// Copyright 2022 Namespace Labs Inc; All rights reserved.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.

package cluster

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestBuck2Address(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		endpoint string
		address  string
		tls      bool
		wantErr  bool
	}{
		{"grpcs://storage.example:443", "grpc://storage.example:443", true, false},
		{"https://storage.example:443", "grpc://storage.example:443", true, false},
		{"grpc://localhost:8980", "grpc://localhost:8980", false, false},
		{"storage.example:443", "grpc://storage.example:443", true, false},
		{"", "", false, true},
		{"unix://storage.example", "", false, true},
		{"grpcs://", "", false, true},
		{"grpcs://storage.example:443\n[other]", "", false, true},
	} {
		address, tls, err := buck2Address(tc.endpoint)
		if tc.wantErr {
			if err == nil {
				t.Errorf("buck2Address(%q) = (%q, %t), want error", tc.endpoint, address, tls)
			}
			continue
		}
		if err != nil || address != tc.address || tls != tc.tls {
			t.Errorf("buck2Address(%q) = (%q, %t, %v), want (%q, %t, nil)", tc.endpoint, address, tls, err, tc.address, tc.tls)
		}
	}
}

func TestToBuck2Config(t *testing.T) {
	t.Parallel()
	out, err := buck2ExecutionSetup("grpcs://scheduler.example:443", "grpcs://storage.example:443", "")
	if err != nil {
		t.Fatal(err)
	}
	out.StaticToken = "tok123"
	config, err := toBuck2Config(out)
	if err != nil {
		t.Fatal(err)
	}
	want := `# Generated by nsc; do not edit.

[buck2_re_client]
engine_address = grpc://scheduler.example:443
action_cache_address = grpc://storage.example:443
cas_address = grpc://storage.example:443
tls = true
http_headers = x-nsc-ingress-auth:Bearer tok123
`
	if got := string(config); got != want {
		t.Fatalf("config =\n%s\nwant:\n%s", got, want)
	}
}

func TestToBuck2ConfigRejectsUnsafeValues(t *testing.T) {
	t.Parallel()
	base, err := buck2CacheOnlySetup("grpcs://storage.example:443", "")
	if err != nil {
		t.Fatal(err)
	}
	for _, token := range []string{"tok,123", "tok$HOME", "tok\n123", "tok\r123"} {
		out := base
		out.StaticToken = token
		if _, err := toBuck2Config(out); err == nil {
			t.Errorf("token %q was accepted", token)
		}
	}
	out := base
	out.StaticToken = "token"
	out.TLSClientCert = "/tmp/client.pem"
	if _, err := toBuck2Config(out); err == nil || !strings.Contains(err.Error(), "both static and mTLS") {
		t.Fatalf("conflicting credentials error = %v", err)
	}
}

func TestResolveBuck2ConfigPath(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	path, isDefault, err := resolveBuck2ConfigPath("")
	if err != nil {
		t.Fatal(err)
	}
	if want := filepath.Join(home, ".buckconfig.d", "50-namespace"); path != want || !isDefault {
		t.Fatalf("default = (%q, %t), want (%q, true)", path, isDefault, want)
	}
}

func assertCredentialFile(t *testing.T, path, want string) {
	t.Helper()
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile(%q): %v", path, err)
	}
	if string(got) != want {
		t.Fatalf("content of %q = %q, want %q", path, got, want)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("Stat(%q): %v", path, err)
	}
	if got := info.Mode().Perm(); got != 0600 {
		t.Fatalf("mode of %q = %o, want 600", path, got)
	}
}
