// Copyright 2022 Namespace Labs Inc; All rights reserved.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.

package cluster

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/spf13/cobra"
)

type buck2TestTokenSource struct {
	token string
	err   error
	dur   time.Duration
	force bool
}

func (f *buck2TestTokenSource) IssueToken(_ context.Context, dur time.Duration, force bool) (string, error) {
	f.dur = dur
	f.force = force
	return f.token, f.err
}

func TestResolveBuck2ConfigPath(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	path, isDefault, err := resolveBuck2ConfigPath("")
	if err != nil {
		t.Fatalf("resolveBuck2ConfigPath: %v", err)
	}

	// buck2 reads ~/.buckconfig.d, so the default must land there rather than
	// in a temporary directory.
	if want := filepath.Join(home, ".buckconfig.d", "50-namespace"); path != want {
		t.Errorf("default path = %q, want %q", path, want)
	}
	if !isDefault {
		t.Error("expected the resolved path to be reported as the default")
	}

	path, isDefault, err = resolveBuck2ConfigPath("/tmp/explicit")
	if err != nil {
		t.Fatalf("resolveBuck2ConfigPath: %v", err)
	}
	if path != "/tmp/explicit" || isDefault {
		t.Errorf("explicit path = (%q, %t), want (\"/tmp/explicit\", false)", path, isDefault)
	}
}

func TestBuck2Address(t *testing.T) {
	t.Parallel()

	for _, tc := range []struct {
		endpoint string
		address  string
		tls      bool
		wantErr  bool
	}{
		{endpoint: "grpcs://storage.example:443", address: "grpc://storage.example:443", tls: true},
		{endpoint: "https://storage.example:443", address: "grpc://storage.example:443", tls: true},
		{endpoint: "grpc://localhost:8980", address: "grpc://localhost:8980", tls: false},
		{endpoint: "http://localhost:8980", address: "grpc://localhost:8980", tls: false},
		{endpoint: "storage.example:443", address: "grpc://storage.example:443", tls: true},
		{endpoint: "", wantErr: true},
		{endpoint: "unix://storage.example", wantErr: true},
		{endpoint: "grpcs://", wantErr: true},
		{endpoint: "grpcs://storage.example:443\n[other]", wantErr: true},
	} {
		address, tls, err := buck2Address(tc.endpoint)
		if tc.wantErr {
			if err == nil {
				t.Errorf("buck2Address(%q) = (%q, %t), want error", tc.endpoint, address, tls)
			}
			continue
		}

		if err != nil {
			t.Errorf("buck2Address(%q): %v", tc.endpoint, err)
			continue
		}

		if address != tc.address || tls != tc.tls {
			t.Errorf("buck2Address(%q) = (%q, %t), want (%q, %t)", tc.endpoint, address, tls, tc.address, tc.tls)
		}
	}
}

func TestToBuck2ConfigRemoteExecution(t *testing.T) {
	t.Parallel()

	out, err := buck2ExecutionSetup("grpcs://scheduler.example:443", "grpcs://storage.example:443", "")
	if err != nil {
		t.Fatalf("buck2ExecutionSetup: %v", err)
	}

	out.StaticToken = "tok123"

	config, err := toBuck2Config(out)
	if err != nil {
		t.Fatalf("toBuck2Config: %v", err)
	}

	want := `# Generated by nsc; do not edit.

[buck2_re_client]
engine_address = grpc://scheduler.example:443
action_cache_address = grpc://storage.example:443
cas_address = grpc://storage.example:443
tls = true
http_headers = x-nsc-ingress-auth:Bearer tok123
`
	if got := string(config); got != want {
		t.Fatalf("toBuck2Config() =\n%s\nwant:\n%s", got, want)
	}
}

func TestToBuck2ConfigCacheOnly(t *testing.T) {
	t.Parallel()

	out, err := buck2CacheOnlySetup("grpcs://ingress.example:443", "main")
	if err != nil {
		t.Fatalf("buck2CacheOnlySetup: %v", err)
	}

	out.StaticToken = "tok123"

	config, err := toBuck2Config(out)
	if err != nil {
		t.Fatalf("toBuck2Config: %v", err)
	}

	want := `# Generated by nsc; do not edit.

[buck2_re_client]
engine_address = grpc://ingress.example:443
action_cache_address = grpc://ingress.example:443
cas_address = grpc://ingress.example:443
tls = true
instance_name = main
http_headers = x-nsc-ingress-auth:Bearer tok123
`
	if got := string(config); got != want {
		t.Fatalf("toBuck2Config() =\n%s\nwant:\n%s", got, want)
	}
}

func TestToBuck2ConfigMTLS(t *testing.T) {
	t.Parallel()

	out, err := buck2ExecutionSetup("grpcs://scheduler.example:443", "grpcs://storage.example:443", "main")
	if err != nil {
		t.Fatalf("buck2ExecutionSetup: %v", err)
	}
	out.TLSCACerts = "/tmp/ca.pem"
	out.TLSClientCert = "/tmp/client.pem"

	config, err := toBuck2Config(out)
	if err != nil {
		t.Fatalf("toBuck2Config: %v", err)
	}

	want := `# Generated by nsc; do not edit.

[buck2_re_client]
engine_address = grpc://scheduler.example:443
action_cache_address = grpc://storage.example:443
cas_address = grpc://storage.example:443
tls = true
tls_ca_certs = /tmp/ca.pem
tls_client_cert = /tmp/client.pem
instance_name = main
`
	if got := string(config); got != want {
		t.Fatalf("toBuck2Config() =\n%s\nwant:\n%s", got, want)
	}
}

func TestBuck2ExecutionSetupRejectsMixedTLS(t *testing.T) {
	t.Parallel()

	if _, err := buck2ExecutionSetup("grpcs://scheduler.example:443", "grpc://storage.example:8980", ""); err == nil {
		t.Fatal("expected mixed TLS endpoints to be rejected")
	}
}

func TestToBuck2ConfigRejectsUnusableTokens(t *testing.T) {
	t.Parallel()

	base, err := buck2CacheOnlySetup("grpcs://ingress.example:443", "")
	if err != nil {
		t.Fatalf("buck2CacheOnlySetup: %v", err)
	}

	for _, token := range []string{"tok,123", "tok$HOME", "tok\n123", "tok\r123"} {
		out := base
		out.StaticToken = token

		if _, err := toBuck2Config(out); err == nil {
			t.Errorf("expected token %q to be rejected", token)
		}
	}

	out := base
	out.StaticToken = "tok-123_abc.def$"
	if _, err := toBuck2Config(out); err != nil {
		t.Errorf("token with a trailing dollar sign is safe, but was rejected: %v", err)
	}

	out.TLSClientCert = "/tmp/client.pem"
	if _, err := toBuck2Config(out); err == nil || !strings.Contains(err.Error(), "both static and mTLS") {
		t.Errorf("configuration with conflicting credentials returned %v", err)
	}
}

func TestIssueBuck2Token(t *testing.T) {
	t.Parallel()

	source := &buck2TestTokenSource{token: "tok123"}
	out := buck2Setup{}
	if err := issueBuck2Token(context.Background(), source, 90*time.Minute, &out); err != nil {
		t.Fatalf("issueBuck2Token: %v", err)
	}
	if source.dur != 90*time.Minute || source.force {
		t.Fatalf("IssueToken called with (%s, %t), want (90m, false)", source.dur, source.force)
	}
	if out.StaticToken != "tok123" || out.TokenDuration != 90*time.Minute {
		t.Fatalf("setup token fields = (%q, %s), want (tok123, 90m)", out.StaticToken, out.TokenDuration)
	}

	source = &buck2TestTokenSource{err: errors.New("no token")}
	if err := issueBuck2Token(context.Background(), source, time.Hour, &buck2Setup{}); err == nil || !strings.Contains(err.Error(), "failed to issue bearer token") {
		t.Fatalf("issueBuck2Token error = %v, want wrapped source error", err)
	}

	source = &buck2TestTokenSource{token: "bad,token"}
	if err := issueBuck2Token(context.Background(), source, time.Hour, &buck2Setup{}); err == nil || !strings.Contains(err.Error(), "cannot carry") {
		t.Fatalf("issueBuck2Token error = %v, want invalid header error", err)
	}
}

func TestSetBuck2ClientIdentity(t *testing.T) {
	t.Parallel()

	out := buck2Setup{}
	if err := setBuck2ClientIdentity(&out, []byte("certificate"), []byte("private-key")); err != nil {
		t.Fatalf("setBuck2ClientIdentity: %v", err)
	}
	if got, want := string(out.clientIdentity), "certificate\nprivate-key"; got != want {
		t.Fatalf("client identity = %q, want %q", got, want)
	}

	for _, tc := range []struct {
		certificate []byte
		privateKey  []byte
	}{
		{privateKey: []byte("private-key")},
		{certificate: []byte("certificate")},
	} {
		if err := setBuck2ClientIdentity(&buck2Setup{}, tc.certificate, tc.privateKey); err == nil {
			t.Errorf("setBuck2ClientIdentity(%q, %q) succeeded, want error", tc.certificate, tc.privateKey)
		}
	}
}

func TestBuck2ReadinessConfig(t *testing.T) {
	t.Parallel()

	static, cleanup, err := buck2ReadinessConfig("grpcs://cache.example", buck2Setup{StaticToken: "token"})
	if err != nil {
		t.Fatalf("buck2ReadinessConfig(static): %v", err)
	}
	defer cleanup()
	if static.bearerToken != "token" || static.clientCert != "" || static.clientKey != "" {
		t.Fatalf("static readiness config = %#v", static)
	}

	identity := []byte("certificate\nprivate-key")
	mtls, cleanup, err := buck2ReadinessConfig("grpcs://cache.example", buck2Setup{clientIdentity: identity})
	if err != nil {
		t.Fatalf("buck2ReadinessConfig(mTLS): %v", err)
	}
	defer cleanup()
	if mtls.clientCert == "" || mtls.clientCert != mtls.clientKey || mtls.bearerToken != "" {
		t.Fatalf("mTLS readiness config = %#v", mtls)
	}
	assertCredentialFile(t, mtls.clientCert, string(identity))
}

func TestValidateBuck2SetupFlags(t *testing.T) {
	t.Parallel()

	for _, tc := range []struct {
		name         string
		output       string
		tokenDur     time.Duration
		instanceName string
		wantErr      string
	}{
		{name: "plain", output: "plain", tokenDur: time.Hour},
		{name: "json", output: "json", tokenDur: time.Hour},
		{name: "bad output", output: "yaml", tokenDur: time.Hour, wantErr: "unsupported output format"},
		{name: "zero duration", output: "plain", wantErr: "must be greater than zero"},
		{name: "negative duration", output: "plain", tokenDur: -time.Second, wantErr: "must be greater than zero"},
		{name: "instance injection", output: "plain", tokenDur: time.Hour, instanceName: "main\n[other]", wantErr: "must not contain a newline"},
		{name: "instance environment expansion", output: "plain", tokenDur: time.Hour, instanceName: "$HOME", wantErr: "would expand as an environment variable"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			err := validateBuck2SetupFlags(tc.output, tc.tokenDur, tc.instanceName)
			if tc.wantErr == "" {
				if err != nil {
					t.Fatalf("validateBuck2SetupFlags() error = %v", err)
				}
				return
			}
			if err == nil || !strings.Contains(err.Error(), tc.wantErr) {
				t.Fatalf("validateBuck2SetupFlags() error = %v, want error containing %q", err, tc.wantErr)
			}
		})
	}
}

func TestBuck2CommandTree(t *testing.T) {
	t.Parallel()

	for _, path := range [][]string{{"setup"}, {"cache", "setup"}} {
		cmd, args, err := NewBuck2Cmd().Find(path)
		if err != nil {
			t.Fatalf("Find(%v): %v", path, err)
		}
		if len(args) != 0 || cmd.Name() != "setup" {
			t.Fatalf("Find(%v) = (%q, %v), want setup with no remaining args", path, cmd.Name(), args)
		}
		if cmd.Flag("buckconfig") == nil || cmd.Flag("static") == nil || cmd.Flag("static_token_duration") == nil {
			t.Fatalf("Find(%v) is missing Buck2 setup flags", path)
		}
	}

	cmd, args, err := NewBuck2CacheCmd().Find([]string{"setup"})
	if err != nil || len(args) != 0 || cmd.Name() != "setup" {
		t.Fatalf("cache alias Find(setup) = (%q, %v, %v)", cmd.Name(), args, err)
	}
}

func TestBuck2CommandsRejectInvalidInputBeforeProvisioning(t *testing.T) {
	t.Parallel()

	for _, tc := range []struct {
		name string
		cmd  func() *cobra.Command
		args []string
		want string
	}{
		{
			name: "execution positional argument",
			cmd:  NewBuck2Cmd,
			args: []string{"setup", "unexpected"},
			want: "unknown command",
		},
		{
			name: "cache invalid output",
			cmd:  NewBuck2CacheCmd,
			args: []string{"setup", "--output=yaml"},
			want: "unsupported output format",
		},
		{
			name: "execution invalid duration",
			cmd:  NewBuck2Cmd,
			args: []string{"setup", "--static_token_duration=0s"},
			want: "must be greater than zero",
		},
		{
			name: "execution read-only",
			cmd:  NewBuck2Cmd,
			args: []string{"setup", "--storage=read-only"},
			want: "requires --remote=false",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			cmd := tc.cmd()
			cmd.SetArgs(tc.args)
			err := cmd.ExecuteContext(context.Background())
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("ExecuteContext() error = %v, want error containing %q", err, tc.want)
			}
		})
	}
}

func TestWriteCredentialFile(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "nested", "buckconfig")
	if err := writeCredentialFile(path, []byte("first")); err != nil {
		t.Fatalf("writeCredentialFile(new): %v", err)
	}
	assertCredentialFile(t, path, "first")

	if err := os.Chmod(path, 0644); err != nil {
		t.Fatalf("Chmod: %v", err)
	}
	if err := writeCredentialFile(path, []byte("second")); err != nil {
		t.Fatalf("writeCredentialFile(existing): %v", err)
	}
	assertCredentialFile(t, path, "second")
}

func TestEmitBuck2MTLSConfig(t *testing.T) {
	t.Parallel()

	configPath := filepath.Join(t.TempDir(), ".buckconfig.local")
	out, err := buck2CacheOnlySetup("grpcs://cache.example:443", "")
	if err != nil {
		t.Fatalf("buck2CacheOnlySetup: %v", err)
	}
	out.clientIdentity = []byte("certificate\nprivate-key")
	out.serverCAPem = []byte("ca-certificate")

	if err := emitBuck2Config(context.Background(), out, configPath, "json", "remote cache"); err != nil {
		t.Fatalf("emitBuck2Config: %v", err)
	}

	identityPath, err := filepath.Abs(configPath + ".tls.pem")
	if err != nil {
		t.Fatalf("filepath.Abs: %v", err)
	}
	caPath, err := filepath.Abs(configPath + ".ca.pem")
	if err != nil {
		t.Fatalf("filepath.Abs: %v", err)
	}
	assertCredentialFile(t, identityPath, "certificate\nprivate-key")
	assertCredentialFile(t, caPath, "ca-certificate")

	config, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("ReadFile(config): %v", err)
	}
	for _, want := range []string{
		"tls_ca_certs = " + caPath + "\n",
		"tls_client_cert = " + identityPath + "\n",
	} {
		if !strings.Contains(string(config), want) {
			t.Errorf("config %q does not contain %q", config, want)
		}
	}
}

func assertCredentialFile(t *testing.T, path, want string) {
	t.Helper()

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if string(got) != want {
		t.Errorf("content = %q, want %q", got, want)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("Stat: %v", err)
	}
	if got := info.Mode().Perm(); got != 0600 {
		t.Errorf("permissions = %#o, want 0600", got)
	}
}
