load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "cluster",
    srcs = [
        "artifact.go",
        "attachdocker.go",
        "bazel.go",
        "bazel_rbe.go",
        "bazel_readiness.go",
        "bazelcredhelper.go",
        "build.go",
        "build_logs.go",
        "build_resolve.go",
        "build_ssh.go",
        "buildkit.go",
        "buildproxy.go",
        "buildx.go",
        "buildx_workers_def.go",
        "cmd.go",
        "create.go",
        "createtoken.go",
        "describe.go",
        "destroy.go",
        "docker.go",
        "egress.go",
        "execscoped.go",
        "expose.go",
        "extendduration.go",
        "generatereport.go",
        "git.go",
        "gitcheckout.go",
        "gradle.go",
        "grpcproxy.go",
        "history.go",
        "ingress.go",
        "kubectl.go",
        "logs.go",
        "machinetype.go",
        "metadata.go",
        "pants.go",
        "portforward.go",
        "proxy.go",
        "proxying.go",
        "rdp.go",
        "registry.go",
        "release.go",
        "remote.go",
        "reservation.go",
        "run.go",
        "sccache.go",
        "secrets.go",
        "server_side_buildx.go",
        "ssh.go",
        "turborepo.go",
        "unixsockproxy.go",
        "vnc.go",
        "volume.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/cli/cmd/cluster",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/atomic",
        "//framework/build/buildkit",
        "//framework/console/termios",
        "//framework/netcopy",
        "//framework/rpcerrors",
        "//framework/rpcerrors/multierr",
        "//internal/artifacts/oci",
        "//internal/build/buildkit/bkkeychain",
        "//internal/buildkite",
        "//internal/cli/cmd/cluster/buildxstore",
        "//internal/cli/fncobra",
        "//internal/cli/fncobra/name",
        "//internal/console",
        "//internal/console/colors",
        "//internal/console/tui",
        "//internal/executor",
        "//internal/files",
        "//internal/fnapi",
        "//internal/fnerrors",
        "//internal/fnnet",
        "//internal/github/env",
        "//internal/localexec",
        "//internal/parsing/platform",
        "//internal/process",
        "//internal/providers/nscloud/api",
        "//internal/providers/nscloud/api/private",
        "//internal/providers/nscloud/api/public",
        "//internal/providers/nscloud/ctl",
        "//internal/providers/nscloud/endpoint",
        "//internal/providers/nscloud/metadata",
        "//internal/sdk/buildctl",
        "//internal/sdk/host",
        "//internal/sdk/kubectl",
        "//internal/workspace/dirs",
        "//std/tasks",
        "@build_buf_gen_go_namespace_bazel_protocolbuffers_go//build/bazel/remote/execution/v2:execution",
        "@build_buf_gen_go_namespace_cloud_grpc_go//proto/namespace/cloud/integrations/bazel/v1beta/bazelv1betagrpc",
        "@build_buf_gen_go_namespace_cloud_protocolbuffers_go//proto/namespace/cloud/integrations/bazel/v1beta",
        "@com_connectrpc_connect//:connect",
        "@com_github_araddon_dateparse//:dateparse",
        "@com_github_aws_smithy_go//ptr",
        "@com_github_cenkalti_backoff//:backoff",
        "@com_github_cenkalti_backoff_v4//:backoff",
        "@com_github_charmbracelet_lipgloss//:lipgloss",
        "@com_github_containerd_console//:console",
        "@com_github_containerd_containerd_v2//client",
        "@com_github_containerd_containerd_v2//pkg/namespaces",
        "@com_github_containerd_errdefs//:errdefs",
        "@com_github_containerd_go_cni//:go-cni",
        "@com_github_docker_cli//cli/command",
        "@com_github_docker_cli//cli/config",
        "@com_github_docker_cli//cli/config/configfile",
        "@com_github_docker_cli//cli/config/types",
        "@com_github_docker_cli//cli/context/docker",
        "@com_github_docker_cli//cli/context/store",
        "@com_github_docker_cli//cli/flags",
        "@com_github_docker_go_units//:go-units",
        "@com_github_dustin_go_humanize//:go-humanize",
        "@com_github_golang_protobuf//proto",
        "@com_github_google_go_containerregistry//pkg/name",
        "@com_github_google_go_containerregistry//pkg/v1/remote",
        "@com_github_mattn_go_isatty//:go-isatty",
        "@com_github_mattn_go_zglob//:go-zglob",
        "@com_github_moby_buildkit//api/services/control",
        "@com_github_moby_buildkit//api/types",
        "@com_github_moby_buildkit//client",
        "@com_github_moby_buildkit//client/llb",
        "@com_github_moby_buildkit//cmd/buildctl/build",
        "@com_github_moby_buildkit//frontend/dockerui",
        "@com_github_moby_buildkit//identity",
        "@com_github_moby_buildkit//session",
        "@com_github_moby_buildkit//session/auth",
        "@com_github_moby_buildkit//session/auth/authprovider",
        "@com_github_moby_buildkit//session/secrets/secretsprovider",
        "@com_github_moby_buildkit//util/progress/progressui",
        "@com_github_moby_buildkit//util/progress/progresswriter",
        "@com_github_moby_moby_api//types/container",
        "@com_github_moby_moby_client//:client",
        "@com_github_muesli_reflow//wordwrap",
        "@com_github_natefinch_atomic//:atomic",
        "@com_github_opencontainers_image_spec//specs-go/v1:specs-go",
        "@com_github_pelletier_go_toml_v2//:go-toml",
        "@com_github_pkg_browser//:browser",
        "@com_github_pkg_errors//:errors",
        "@com_github_spf13_cobra//:cobra",
        "@com_github_spf13_pflag//:pflag",
        "@com_github_tonistiigi_go_csvvalue//:go-csvvalue",
        "@dev_namespacelabs_go_ids//:go-ids",
        "@dev_namespacelabs_integrations//api",
        "@dev_namespacelabs_integrations//api/builds",
        "@dev_namespacelabs_integrations//api/compute",
        "@dev_namespacelabs_integrations//api/iam",
        "@dev_namespacelabs_integrations//api/registry",
        "@dev_namespacelabs_integrations//api/storage",
        "@dev_namespacelabs_integrations//nsc/grpcapi",
        "@dev_namespacelabs_integrations//proto/namespace/cloud/builder/v1beta",
        "@dev_namespacelabs_integrations//proto/namespace/cloud/buildkite",
        "@dev_namespacelabs_integrations//proto/namespace/cloud/compute/v1beta",
        "@dev_namespacelabs_integrations//proto/namespace/cloud/github/v1beta",
        "@dev_namespacelabs_integrations//proto/namespace/cloud/iam/v1beta",
        "@dev_namespacelabs_integrations//proto/namespace/cloud/integrations/gradle/v1beta",
        "@dev_namespacelabs_integrations//proto/namespace/cloud/integrations/gradle/v1beta/gradlev1betaconnect",
        "@dev_namespacelabs_integrations//proto/namespace/cloud/integrations/httpcache/v1beta",
        "@dev_namespacelabs_integrations//proto/namespace/cloud/integrations/httpcache/v1beta/httpcachev1betaconnect",
        "@dev_namespacelabs_integrations//proto/namespace/cloud/registry/v1beta",
        "@dev_namespacelabs_integrations//proto/namespace/cloud/storage/v1beta",
        "@dev_namespacelabs_integrations//proto/namespace/experimental/compute",
        "@dev_namespacelabs_integrations//proto/namespace/private/instance",
        "@dev_namespacelabs_integrations//proto/namespace/stdlib",
        "@dev_namespacelabs_integrations//storage/downloader",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_client_go//kubernetes",
        "@io_k8s_client_go//tools/clientcmd",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//connectivity",
        "@org_golang_google_grpc//credentials",
        "@org_golang_google_grpc//credentials/insecure",
        "@org_golang_google_grpc//keepalive",
        "@org_golang_google_grpc//metadata",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//encoding/protojson",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//types/known/durationpb",
        "@org_golang_google_protobuf//types/known/emptypb",
        "@org_golang_google_protobuf//types/known/timestamppb",
        "@org_golang_google_protobuf//types/known/wrapperspb",
        "@org_golang_x_crypto//ssh",
        "@org_golang_x_crypto//ssh/agent",
        "@org_golang_x_exp//maps",
        "@org_golang_x_exp//slices",
        "@org_golang_x_sync//errgroup",
        "@org_golang_x_term//:term",
        "@org_golang_x_text//cases",
        "@org_golang_x_text//language",
    ],
)
