load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "netcopy",
    srcs = ["netcopy.go"],
    importpath = "namespacelabs.dev/foundation/framework/netcopy",
    visibility = ["//visibility:public"],
    deps = [
        "//framework/rpcerrors/multierr",
        "@af_inet_tcpproxy//:tcpproxy",
    ],
)
