load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "kubectl",
    srcs = [
        "kubeconfig.go",
        "kubectl.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/sdk/kubectl",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/artifacts",
        "//internal/artifacts/unpack",
        "//internal/compute",
        "//internal/fnerrors",
        "//internal/workspace/dirs",
        "//schema",
        "//std/tasks",
        "@com_github_opencontainers_image_spec//specs-go/v1:specs-go",
        "@io_k8s_client_go//tools/clientcmd",
        "@io_k8s_client_go//tools/clientcmd/api",
    ],
)
