// This file is automatically generated.
package middleware

#Exports: {
	Middleware: {
		name?: string

		#Definition: {
			packageName: "namespacelabs.dev/foundation/std/go/http/middleware"
			type:        "Middleware"
			typeDefinition: {
				"typename": "foundation.std.go.http.middleware.MiddlewareRegistration"
				"source": [
					"provider.proto",
				]
			}
		}
	}
}
