load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "nscloud",
    srcs = [
        "buildcluster.go",
        "cluster.go",
        "provider.pb.go",
        "registry.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/providers/nscloud",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/kubernetes/kubedef",
        "//internal/artifacts/oci",
        "//internal/artifacts/registry",
        "//internal/build/buildkit",
        "//internal/build/registry",
        "//internal/cli/fncobra",
        "//internal/compute",
        "//internal/fnerrors",
        "//internal/networking/ingress/nginx",
        "//internal/protos",
        "//internal/providers/nscloud/api",
        "//internal/providers/nscloud/api/private",
        "//internal/providers/nscloud/ctl",
        "//internal/providers/nscloud/endpoint",
        "//internal/runtime",
        "//internal/runtime/kubernetes",
        "//internal/runtime/kubernetes/client",
        "//schema",
        "//schema/runtime",
        "//std/cfg",
        "//std/tasks",
        "//universe/nscloud/configuration",
        "@com_github_spf13_pflag//:pflag",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//runtime/protoimpl",
    ],
)
