// This file is automatically generated.
package grpc

#Exports: {
	GrpcRegistrar: {
		#Definition: {
			packageName: "namespacelabs.dev/foundation/std/nodejs/grpc"
			type:        "GrpcRegistrar"
			typeDefinition: {
				"typename": "std.nodejs.grpc.NoArgs"
				"source": [
					"provider.proto",
				]
			}
		}
	}
}
