// This file was automatically generated by Namespace.
// DO NOT EDIT. To update, re-run `ns generate`.

package base

import (
	"context"
	fncore "namespacelabs.dev/foundation/std/core"
	"namespacelabs.dev/foundation/std/go/core"
	"namespacelabs.dev/foundation/std/monitoring/tracing"
)

// Dependencies that are instantiated once for the lifetime of the extension.
type ExtensionDeps struct {
	OpenTelemetry  tracing.DeferredTracerProvider
	ReadinessCheck core.Check
}

type _checkProvideWireDatabase func(context.Context, *WireDatabaseArgs, ExtensionDeps) (WireDatabase, error)

var _ _checkProvideWireDatabase = ProvideWireDatabase

var (
	Package__26debk = &core.Package{
		PackageName: "namespacelabs.dev/foundation/universe/db/postgres/internal/base",
	}

	Provider__26debk = core.Provider{
		Package:     Package__26debk,
		Instantiate: makeDeps__26debk,
	}
)

func makeDeps__26debk(ctx context.Context, di core.Dependencies) (_ interface{}, err error) {
	var deps ExtensionDeps

	if err := di.Instantiate(ctx, tracing.Provider__70o2mm, func(ctx context.Context, v interface{}) (err error) {
		if deps.OpenTelemetry, err = tracing.ProvideTracerProvider(ctx, nil, v.(tracing.ExtensionDeps)); err != nil {
			return err
		}
		return nil
	}); err != nil {
		return nil, err
	}

	if deps.ReadinessCheck, err = fncore.ProvideReadinessCheck(ctx, nil); err != nil {
		return nil, err
	}

	return deps, nil
}
