load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "shellscript",
    srcs = ["shellscript.go"],
    importpath = "namespacelabs.dev/foundation/internal/parsing/integration/shellscript",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/fnerrors",
        "//internal/parsing/integration/api",
        "//schema",
        "//std/pkggraph",
    ],
)
