load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "kubedef",
    srcs = [
        "deploymentid.go",
        "details.pb.go",
        "extensions.pb.go",
        "kubecluster.go",
        "kubedef.go",
        "labels.go",
        "op.pb.go",
        "op_ingress.pb.go",
        "planorder.go",
        "podreference.go",
        "storage.pb.go",
        "systeminfo.pb.go",
    ],
    importpath = "namespacelabs.dev/foundation/framework/kubernetes/kubedef",
    visibility = ["//visibility:public"],
    deps = [
        "//framework/kubernetes/kubenaming",
        "//framework/kubernetes/kubeobj",
        "//internal/fnerrors",
        "//internal/runtime",
        "//internal/runtime/kubernetes/client",
        "//schema",
        "//schema/runtime",
        "//std/execution",
        "//std/execution/defs",
        "//std/resources",
        "//std/types",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/runtime/schema",
        "@io_k8s_client_go//applyconfigurations/rbac/v1:rbac",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//runtime/protoimpl",
        "@org_golang_google_protobuf//types/known/anypb",
        "@org_golang_x_exp//maps",
        "@org_golang_x_exp//slices",
    ],
)
