load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "configuration",
    srcs = ["config.pb.go"],
    importpath = "namespacelabs.dev/foundation/universe/k3s/configuration",
    visibility = ["//visibility:public"],
    deps = [
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//runtime/protoimpl",
    ],
)
