load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "fnapi",
    srcs = [
        "bazel.go",
        "buildkite.go",
        "fnapi.go",
        "githubrunners.go",
        "gradle.go",
        "httpcache.go",
        "map.go",
        "naming.go",
        "profile.go",
        "signin.go",
        "tenants.go",
        "tokens.go",
        "versions.go",
        "workload_token_other.go",
        "workload_token_windows.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/fnapi",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/auth",
        "//internal/certificates",
        "//internal/console",
        "//internal/files",
        "//internal/fnerrors",
        "//internal/versions",
        "//schema",
        "//std/tasks",
        "@build_buf_gen_go_namespace_cloud_connectrpc_go//proto/namespace/cloud/integrations/bazel/v1beta/bazelv1betaconnect",
        "@com_connectrpc_connect//:connect",
        "@com_github_cenkalti_backoff//:backoff",
        "@com_github_spf13_pflag//:pflag",
        "@dev_namespacelabs_go_ids//:go-ids",
        "@dev_namespacelabs_integrations//api",
        "@dev_namespacelabs_integrations//api/iam",
        "@dev_namespacelabs_integrations//auth",
        "@dev_namespacelabs_integrations//auth/aws",
        "@dev_namespacelabs_integrations//nsc/apienv",
        "@dev_namespacelabs_integrations//proto/namespace/cloud/buildkite/buildkiteconnect",
        "@dev_namespacelabs_integrations//proto/namespace/cloud/github/v1beta/githubv1betaconnect",
        "@dev_namespacelabs_integrations//proto/namespace/cloud/iam/v1beta",
        "@dev_namespacelabs_integrations//proto/namespace/cloud/integrations/gradle/v1beta/gradlev1betaconnect",
        "@dev_namespacelabs_integrations//proto/namespace/cloud/integrations/httpcache/v1beta/httpcachev1betaconnect",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel_trace//:trace",
        "@org_golang_google_genproto_googleapis_rpc//status",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//types/known/emptypb",
    ] + select({
        "@rules_go//go/platform:windows": [
            "//internal/providers/nscloud/metadata",
        ],
        "//conditions:default": [],
    }),
)
