load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "rpcerrors",
    srcs = ["rpcerrors.go"],
    importpath = "namespacelabs.dev/foundation/framework/rpcerrors",
    visibility = ["//visibility:public"],
    deps = [
        "//public/nscloud/proto/v1:proto",
        "@com_github_go_errors_errors//:errors",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//types/known/anypb",
    ],
)
