load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "configure_lib",
    srcs = ["main.go"],
    embedsrcs = ["config.yaml.tmpl"],
    importpath = "namespacelabs.dev/foundation/universe/networking/k8s-event-exporter/configure",
    visibility = ["//visibility:private"],
    deps = [
        "//framework/kubernetes/kubeblueprint",
        "//framework/kubernetes/kubedef",
        "//framework/kubernetes/kubetool",
        "//framework/provisioning",
        "//internal/fnerrors",
        "//schema",
        "@io_k8s_client_go//applyconfigurations/core/v1:core",
        "@io_k8s_client_go//applyconfigurations/rbac/v1:rbac",
    ],
)

go_binary(
    name = "configure",
    embed = [":configure_lib"],
    visibility = ["//visibility:public"],
)
