load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "eks",
    srcs = [
        "bearertoken.go",
        "client.go",
        "cluster.go",
        "kubeconfig.go",
        "op.pb.go",
        "ops.go",
        "setupautopush.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/providers/aws/eks",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/kubernetes/kubedef",
        "//internal/build/registry",
        "//internal/compute",
        "//internal/executor",
        "//internal/fnerrors",
        "//internal/networking/ingress/nginx",
        "//internal/planning/planninghooks",
        "//internal/providers/aws",
        "//internal/providers/aws/auth",
        "//internal/runtime/kubernetes",
        "//internal/runtime/kubernetes/client",
        "//internal/runtime/rtypes",
        "//schema",
        "//std/cfg",
        "//std/execution",
        "//std/execution/defs",
        "//std/tasks",
        "//universe/aws/configuration/eks",
        "//universe/aws/eks",
        "//universe/aws/iam",
        "@com_github_aws_aws_sdk_go_v2_service_eks//:eks",
        "@com_github_aws_aws_sdk_go_v2_service_eks//types",
        "@com_github_aws_aws_sdk_go_v2_service_iam//:iam",
        "@com_github_aws_aws_sdk_go_v2_service_sts//:sts",
        "@com_github_aws_smithy_go//transport/http",
        "@com_github_keikoproj_aws_auth//pkg/mapper",
        "@io_k8s_client_go//applyconfigurations/rbac/v1:rbac",
        "@io_k8s_client_go//tools/clientcmd/api",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//runtime/protoimpl",
    ],
)
