load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "sdk",
    srcs = [
        "gcloud.go",
        "gocmd.go",
        "sdk.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/cli/cmd/sdk",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/cli/fncobra",
        "//internal/compute",
        "//internal/console",
        "//internal/fnerrors",
        "//internal/integrations/golang/rungo",
        "//internal/localexec",
        "//internal/parsing",
        "//internal/parsing/platform",
        "//internal/runtime/rtypes",
        "//internal/sdk/buildctl",
        "//internal/sdk/gcloud",
        "//internal/sdk/golang",
        "//internal/sdk/grpcurl",
        "//internal/sdk/host",
        "//internal/sdk/k3d",
        "//internal/sdk/kubectl",
        "//internal/sdk/melange",
        "//schema",
        "//std/module",
        "//std/tasks",
        "//std/tasks/idtypes",
        "@com_github_morikuni_aec//:aec",
        "@com_github_opencontainers_image_spec//specs-go/v1:specs-go",
        "@com_github_spf13_cobra//:cobra",
        "@io_k8s_utils//ptr",
        "@org_golang_x_exp//slices",
    ],
)
