// Copyright 2022 Namespace Labs Inc; All rights reserved.
// Licensed under the EARLY ACCESS SOFTWARE LICENSE AGREEMENT
// available at http://github.com/namespacelabs/foundation

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: workspace/tasks/protolog/log.proto

package protolog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	protocol "namespacelabs.dev/foundation/workspace/tasks/protocol"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogLevel int32          `protobuf:"varint,1,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	Task     *protocol.Task `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workspace_tasks_protolog_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_tasks_protolog_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_workspace_tasks_protolog_log_proto_rawDescGZIP(), []int{0}
}

func (x *Log) GetLogLevel() int32 {
	if x != nil {
		return x.LogLevel
	}
	return 0
}

func (x *Log) GetTask() *protocol.Task {
	if x != nil {
		return x.Task
	}
	return nil
}

var File_workspace_tasks_protolog_log_proto protoreflect.FileDescriptor

var file_workspace_tasks_protolog_log_proto_rawDesc = []byte{
	0x0a, 0x22, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2f, 0x74, 0x61, 0x73, 0x6b,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6c, 0x6f, 0x67, 0x2f, 0x6c, 0x6f, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x23, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6c, 0x6f, 0x67, 0x1a, 0x24, 0x77, 0x6f, 0x72, 0x6b, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x61, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x5f, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x12, 0x3d, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x29, 0x2e, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x77,
	0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x74, 0x61,
	0x73, 0x6b, 0x42, 0x37, 0x5a, 0x35, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6c,
	0x61, 0x62, 0x73, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2f, 0x74, 0x61, 0x73,
	0x6b, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6c, 0x6f, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_workspace_tasks_protolog_log_proto_rawDescOnce sync.Once
	file_workspace_tasks_protolog_log_proto_rawDescData = file_workspace_tasks_protolog_log_proto_rawDesc
)

func file_workspace_tasks_protolog_log_proto_rawDescGZIP() []byte {
	file_workspace_tasks_protolog_log_proto_rawDescOnce.Do(func() {
		file_workspace_tasks_protolog_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_workspace_tasks_protolog_log_proto_rawDescData)
	})
	return file_workspace_tasks_protolog_log_proto_rawDescData
}

var file_workspace_tasks_protolog_log_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_workspace_tasks_protolog_log_proto_goTypes = []interface{}{
	(*Log)(nil),           // 0: foundation.workspace.tasks.protolog.Log
	(*protocol.Task)(nil), // 1: foundation.workspace.tasks.protocol.Task
}
var file_workspace_tasks_protolog_log_proto_depIdxs = []int32{
	1, // 0: foundation.workspace.tasks.protolog.Log.task:type_name -> foundation.workspace.tasks.protocol.Task
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_workspace_tasks_protolog_log_proto_init() }
func file_workspace_tasks_protolog_log_proto_init() {
	if File_workspace_tasks_protolog_log_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_workspace_tasks_protolog_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_workspace_tasks_protolog_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workspace_tasks_protolog_log_proto_goTypes,
		DependencyIndexes: file_workspace_tasks_protolog_log_proto_depIdxs,
		MessageInfos:      file_workspace_tasks_protolog_log_proto_msgTypes,
	}.Build()
	File_workspace_tasks_protolog_log_proto = out.File
	file_workspace_tasks_protolog_log_proto_rawDesc = nil
	file_workspace_tasks_protolog_log_proto_goTypes = nil
	file_workspace_tasks_protolog_log_proto_depIdxs = nil
}
