// This file was automatically generated by Namespace.
// DO NOT EDIT. To update, re-run `ns generate`.

package service

import (
	"context"
	"namespacelabs.dev/foundation/std/go/core"
	"namespacelabs.dev/foundation/std/go/server"
)

// Dependencies that are instantiated once for the lifetime of the service.
type ServiceDeps struct {
}

// Verify that WireService is present and has the appropriate type.
type checkWireService func(context.Context, server.Registrar, ServiceDeps)

var _ checkWireService = WireService

var (
	Package__k1rd1l = &core.Package{
		PackageName: "namespacelabs.dev/foundation/internal/orchestration/service",
	}

	Provider__k1rd1l = core.Provider{
		Package:     Package__k1rd1l,
		Instantiate: makeDeps__k1rd1l,
	}
)

func makeDeps__k1rd1l(ctx context.Context, di core.Dependencies) (_ interface{}, err error) {
	var deps ServiceDeps

	return deps, nil
}