// Copyright 2022 Namespace Labs Inc; All rights reserved.
// Licensed under the EARLY ACCESS SOFTWARE LICENSE AGREEMENT
// available at http://github.com/namespacelabs/foundation

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: schema/runtime.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerKind int32

const (
	ContainerKind_CONTAINER_KIND_UNSPECIFIED ContainerKind = 0
	ContainerKind_PRIMARY                    ContainerKind = 1
	ContainerKind_SUPPORT                    ContainerKind = 2
)

// Enum value maps for ContainerKind.
var (
	ContainerKind_name = map[int32]string{
		0: "CONTAINER_KIND_UNSPECIFIED",
		1: "PRIMARY",
		2: "SUPPORT",
	}
	ContainerKind_value = map[string]int32{
		"CONTAINER_KIND_UNSPECIFIED": 0,
		"PRIMARY":                    1,
		"SUPPORT":                    2,
	}
)

func (x ContainerKind) Enum() *ContainerKind {
	p := new(ContainerKind)
	*p = x
	return p
}

func (x ContainerKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerKind) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_runtime_proto_enumTypes[0].Descriptor()
}

func (ContainerKind) Type() protoreflect.EnumType {
	return &file_schema_runtime_proto_enumTypes[0]
}

func (x ContainerKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerKind.Descriptor instead.
func (ContainerKind) EnumDescriptor() ([]byte, []int) {
	return file_schema_runtime_proto_rawDescGZIP(), []int{0}
}

var File_schema_runtime_proto protoreflect.FileDescriptor

var file_schema_runtime_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2a, 0x49, 0x0a, 0x0d, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x4f,
	0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52,
	0x49, 0x4d, 0x41, 0x52, 0x59, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x50, 0x50, 0x4f,
	0x52, 0x54, 0x10, 0x02, 0x42, 0x25, 0x5a, 0x23, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x6c, 0x61, 0x62, 0x73, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_schema_runtime_proto_rawDescOnce sync.Once
	file_schema_runtime_proto_rawDescData = file_schema_runtime_proto_rawDesc
)

func file_schema_runtime_proto_rawDescGZIP() []byte {
	file_schema_runtime_proto_rawDescOnce.Do(func() {
		file_schema_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_runtime_proto_rawDescData)
	})
	return file_schema_runtime_proto_rawDescData
}

var file_schema_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_schema_runtime_proto_goTypes = []interface{}{
	(ContainerKind)(0), // 0: foundation.schema.ContainerKind
}
var file_schema_runtime_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schema_runtime_proto_init() }
func file_schema_runtime_proto_init() {
	if File_schema_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_runtime_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_runtime_proto_goTypes,
		DependencyIndexes: file_schema_runtime_proto_depIdxs,
		EnumInfos:         file_schema_runtime_proto_enumTypes,
	}.Build()
	File_schema_runtime_proto = out.File
	file_schema_runtime_proto_rawDesc = nil
	file_schema_runtime_proto_goTypes = nil
	file_schema_runtime_proto_depIdxs = nil
}
