load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "cmd",
    srcs = [
        "attach.go",
        "build.go",
        "buildbinary.go",
        "cache.go",
        "cmd.go",
        "config.go",
        "debugshell.go",
        "deploy.go",
        "deployment.go",
        "deployplan.go",
        "describe.go",
        "dev.go",
        "doctor.go",
        "fmt.go",
        "generate.go",
        "hydration.go",
        "images.go",
        "keys.go",
        "lint.go",
        "logs.go",
        "ls.go",
        "test.go",
        "unprepare.go",
        "upgrade.go",
        "use.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/cli/cmd",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/planning/render",
        "//framework/rpcerrors/multierr",
        "//internal/artifacts",
        "//internal/artifacts/oci",
        "//internal/artifacts/registry",
        "//internal/auth",
        "//internal/build",
        "//internal/build/assets",
        "//internal/build/binary",
        "//internal/build/buildkit",
        "//internal/build/registry",
        "//internal/buildkite",
        "//internal/cli/cmd/auth",
        "//internal/cli/cmd/cluster",
        "//internal/cli/cmd/eks",
        "//internal/cli/cmd/lsp",
        "//internal/cli/cmd/mod",
        "//internal/cli/cmd/prepare",
        "//internal/cli/cmd/sdk",
        "//internal/cli/cmd/secrets",
        "//internal/cli/cmd/tools",
        "//internal/cli/cmd/version",
        "//internal/cli/fncobra",
        "//internal/cli/fncobra/planningargs",
        "//internal/cli/keyboard",
        "//internal/cli/nsboot",
        "//internal/codegen/genpackage",
        "//internal/codegen/protos/resolver",
        "//internal/compute",
        "//internal/console",
        "//internal/console/colors",
        "//internal/console/tui",
        "//internal/debugshell",
        "//internal/dependencies/pins",
        "//internal/devsession",
        "//internal/environment",
        "//internal/executor",
        "//internal/fnapi",
        "//internal/fnerrors",
        "//internal/fnerrors/env",
        "//internal/fnerrors/format",
        "//internal/fnfs",
        "//internal/fnfs/digestfs",
        "//internal/fnfs/memfs",
        "//internal/frontend/cuefrontend",
        "//internal/frontend/fncue",
        "//internal/integrations/golang",
        "//internal/keys",
        "//internal/logs/logtail",
        "//internal/observers",
        "//internal/parsing",
        "//internal/parsing/devhost",
        "//internal/parsing/platform",
        "//internal/planning",
        "//internal/planning/config",
        "//internal/planning/deploy",
        "//internal/planning/deploy/storage",
        "//internal/planning/deploy/view",
        "//internal/planning/eval",
        "//internal/protos",
        "//internal/runtime",
        "//internal/runtime/docker",
        "//internal/runtime/kubernetes",
        "//internal/runtime/kubernetes/kubeops",
        "//internal/runtime/rtypes",
        "//internal/storedrun",
        "//internal/testing",
        "//internal/uniquestrings",
        "//internal/unprepare",
        "//internal/workspace/dirs",
        "//orchestration",
        "//schema",
        "//schema/storage",
        "//std/cfg",
        "//std/module",
        "//std/pkggraph",
        "//std/tasks",
        "//std/tasks/idtypes",
        "//universe/db/postgres",
        "@com_github_docker_go_units//:go-units",
        "@com_github_dustin_go_humanize//:go-humanize",
        "@com_github_google_go_containerregistry//pkg/name",
        "@com_github_google_go_containerregistry//pkg/v1/daemon",
        "@com_github_google_go_containerregistry//pkg/v1/mutate",
        "@com_github_google_go_containerregistry//pkg/v1/tarball",
        "@com_github_gorilla_mux//:mux",
        "@com_github_kr_text//:text",
        "@com_github_moby_buildkit//client/llb",
        "@com_github_moby_moby_api//types/system",
        "@com_github_opencontainers_image_spec//specs-go/v1:specs-go",
        "@com_github_philopon_go_toposort//:go-toposort",
        "@com_github_spf13_cobra//:cobra",
        "@com_github_spf13_pflag//:pflag",
        "@com_github_spf13_viper//:viper",
        "@dev_namespacelabs_go_ids//:go-ids",
        "@io_filippo_age//:age",
        "@io_k8s_utils//ptr",
        "@org_cuelang_go//cue/ast",
        "@org_cuelang_go//cue/format",
        "@org_golang_google_protobuf//encoding/protojson",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//reflect/protoregistry",
        "@org_golang_google_protobuf//types/known/anypb",
        "@org_golang_x_exp//slices",
    ],
)
