// Copyright 2022 Namespace Labs Inc; All rights reserved.
// Licensed under the EARLY ACCESS SOFTWARE LICENSE AGREEMENT
// available at http://github.com/namespacelabs/foundation

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: languages/golang/generate.proto

package golang

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Instantiate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Package   string                   `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Typename  string                   `protobuf:"bytes,2,opt,name=typename,proto3" json:"typename,omitempty"`
	Method    string                   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Arguments []*Instantiate_MethodArg `protobuf:"bytes,4,rep,name=arguments,proto3" json:"arguments,omitempty"`
}

func (x *Instantiate) Reset() {
	*x = Instantiate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_languages_golang_generate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Instantiate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instantiate) ProtoMessage() {}

func (x *Instantiate) ProtoReflect() protoreflect.Message {
	mi := &file_languages_golang_generate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instantiate.ProtoReflect.Descriptor instead.
func (*Instantiate) Descriptor() ([]byte, []int) {
	return file_languages_golang_generate_proto_rawDescGZIP(), []int{0}
}

func (x *Instantiate) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Instantiate) GetTypename() string {
	if x != nil {
		return x.Typename
	}
	return ""
}

func (x *Instantiate) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Instantiate) GetArguments() []*Instantiate_MethodArg {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type FrameworkExt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Which Go version this server is compiled against (computed).
	GoVersion string `protobuf:"bytes,1,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	// The go module of the server.
	GoModule string `protobuf:"bytes,2,opt,name=go_module,json=goModule,proto3" json:"go_module,omitempty"`
	// Relative path to go.mod.
	GoModulePath string `protobuf:"bytes,3,opt,name=go_module_path,json=goModulePath,proto3" json:"go_module_path,omitempty"`
}

func (x *FrameworkExt) Reset() {
	*x = FrameworkExt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_languages_golang_generate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FrameworkExt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameworkExt) ProtoMessage() {}

func (x *FrameworkExt) ProtoReflect() protoreflect.Message {
	mi := &file_languages_golang_generate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameworkExt.ProtoReflect.Descriptor instead.
func (*FrameworkExt) Descriptor() ([]byte, []int) {
	return file_languages_golang_generate_proto_rawDescGZIP(), []int{1}
}

func (x *FrameworkExt) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *FrameworkExt) GetGoModule() string {
	if x != nil {
		return x.GoModule
	}
	return ""
}

func (x *FrameworkExt) GetGoModulePath() string {
	if x != nil {
		return x.GoModulePath
	}
	return ""
}

type Instantiate_MethodArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref string `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
}

func (x *Instantiate_MethodArg) Reset() {
	*x = Instantiate_MethodArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_languages_golang_generate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Instantiate_MethodArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instantiate_MethodArg) ProtoMessage() {}

func (x *Instantiate_MethodArg) ProtoReflect() protoreflect.Message {
	mi := &file_languages_golang_generate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instantiate_MethodArg.ProtoReflect.Descriptor instead.
func (*Instantiate_MethodArg) Descriptor() ([]byte, []int) {
	return file_languages_golang_generate_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Instantiate_MethodArg) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

var File_languages_golang_generate_proto protoreflect.FileDescriptor

var file_languages_golang_generate_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0x6c, 0x61,
	0x6e, 0x67, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x1b, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x6c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x22, 0xcc,
	0x01, 0x0a, 0x0b, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x69, 0x61, 0x74, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x79, 0x70, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x79, 0x70, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x50, 0x0a, 0x09,
	0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x32, 0x2e, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x74, 0x69, 0x61, 0x74, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x41, 0x72, 0x67, 0x52, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x1d,
	0x0a, 0x09, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x41, 0x72, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x66, 0x22, 0x70, 0x0a,
	0x0c, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x45, 0x78, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x67, 0x6f, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x67, 0x6f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09,
	0x67, 0x6f, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x67, 0x6f, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x67, 0x6f, 0x5f,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x67, 0x6f, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x42,
	0x2f, 0x5a, 0x2d, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6c, 0x61, 0x62, 0x73,
	0x2e, 0x64, 0x65, 0x76, 0x2f, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_languages_golang_generate_proto_rawDescOnce sync.Once
	file_languages_golang_generate_proto_rawDescData = file_languages_golang_generate_proto_rawDesc
)

func file_languages_golang_generate_proto_rawDescGZIP() []byte {
	file_languages_golang_generate_proto_rawDescOnce.Do(func() {
		file_languages_golang_generate_proto_rawDescData = protoimpl.X.CompressGZIP(file_languages_golang_generate_proto_rawDescData)
	})
	return file_languages_golang_generate_proto_rawDescData
}

var file_languages_golang_generate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_languages_golang_generate_proto_goTypes = []interface{}{
	(*Instantiate)(nil),           // 0: foundation.languages.golang.Instantiate
	(*FrameworkExt)(nil),          // 1: foundation.languages.golang.FrameworkExt
	(*Instantiate_MethodArg)(nil), // 2: foundation.languages.golang.Instantiate.MethodArg
}
var file_languages_golang_generate_proto_depIdxs = []int32{
	2, // 0: foundation.languages.golang.Instantiate.arguments:type_name -> foundation.languages.golang.Instantiate.MethodArg
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_languages_golang_generate_proto_init() }
func file_languages_golang_generate_proto_init() {
	if File_languages_golang_generate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_languages_golang_generate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Instantiate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_languages_golang_generate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FrameworkExt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_languages_golang_generate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Instantiate_MethodArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_languages_golang_generate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_languages_golang_generate_proto_goTypes,
		DependencyIndexes: file_languages_golang_generate_proto_depIdxs,
		MessageInfos:      file_languages_golang_generate_proto_msgTypes,
	}.Build()
	File_languages_golang_generate_proto = out.File
	file_languages_golang_generate_proto_rawDesc = nil
	file_languages_golang_generate_proto_goTypes = nil
	file_languages_golang_generate_proto_depIdxs = nil
}