load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "integrations",
    srcs = ["types.go"],
    importpath = "namespacelabs.dev/foundation/internal/integrations",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/build",
        "//internal/build/assets",
        "//internal/fnfs/workspace/wsremote",
        "//internal/parsing",
        "//internal/planning",
        "//internal/runtime",
        "//internal/wscontents",
        "//schema",
        "//std/cfg",
        "//std/pkggraph",
    ],
)
