load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "compute",
    srcs = [
        "bytedigest.go",
        "bytestream.go",
        "collect.go",
        "computable.go",
        "consume.go",
        "continuous.go",
        "digest.go",
        "explain.go",
        "future.go",
        "graph.go",
        "inline.go",
        "inputs.go",
        "output.go",
        "protodigest.go",
        "resolved.go",
        "serialized.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/compute",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/sync/ctxmutex",
        "//internal/artifacts/contentstore",
        "//internal/bytestream",
        "//internal/console",
        "//internal/executor",
        "//internal/fnerrors",
        "//internal/versions",
        "//internal/workspace/dirs",
        "//schema",
        "//std/tasks",
        "@com_github_kr_text//:text",
        "@dev_namespacelabs_go_ids//:go-ids",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel_trace//:trace",
        "@org_golang_google_protobuf//encoding/prototext",
        "@org_golang_google_protobuf//proto",
    ],
)
