// This file is automatically generated.
package grpc

#Exports: {
	Conn: {
		packageName: "namespacelabs.dev/foundation/std/go/grpc"
		type:        "Conn"
		typeDefinition: {
			"typename": "foundation.std.go.grpc.Conn"
			"source": [
				"provider.proto",
			]
		}
		with: {
			packageName?:   string
			protoTypename?: string
		}
	}
}
