apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: httpgrpctranscoders.k8s.namespacelabs.dev
spec:
  group: k8s.namespacelabs.dev
  scope: Namespaced
  names:
    plural: httpgrpctranscoders
    singular: httpgrpctranscoder
    kind: HttpGrpcTranscoder
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      # subresources describes the subresources for custom resources.
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              description: Holds the desired state of the Configuration (from the client).
              type: object
              properties:
                fullyQualifiedProtoServiceName:
                  description: Fully qualified `package.service` name of the exported gRPC service. For E.g. `api.todos.TodosService`.
                  type: string
                serviceAddress:
                  description: Upstream address of the gRPC service. For E.g. `127.0.0.1`.
                  type: string
                servicePort:
                  description: Upstream port that the HTTP listener routes to for paths matching `/serviceName`.
                  type: integer
                encodedProtoDescriptor:
                  description: Base64 encoded `descriptorpb.FileDescriptorSet` of the gRPC service .proto file and it's transitive .proto dependencies.
                  type: string
            status:
              description: Holds the applied state of the Configuration (from the server).
              type: object
              properties:
                conditions: 
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        type: string 
                      status:
                        description: Status of the condition, one of `True`, `False`, or `Unknown`.
                        type: string
                      observedGeneration:
                        description: Represents the .metadata.generation that the condition was based on.
                        type: integer
                      lastTransitionTime:
                        description: Last time the condition transitioned from one status to another.
                        type: string
                      reason:
                        description: Contains a programmatic identifier indicating the reason for the condition's last transition and is populated normally for errors.
                        type: string
                      message:
                        description: Human readable message indicating details about the transition. Like `description`, this is populated normally for errors.
                        type: string
