// This file was automatically generated by Namespace.
// DO NOT EDIT. To update, re-run `ns generate`.

package gencreds

import (
	"context"
	"namespacelabs.dev/foundation/std/go/core"
	"namespacelabs.dev/foundation/std/secrets"
)

// Dependencies that are instantiated once for the lifetime of the extension.
type ExtensionDeps struct {
	Password *secrets.Value
}

type _checkProvideCreds func(context.Context, *CredsRequest, ExtensionDeps) (*Creds, error)

var _ _checkProvideCreds = ProvideCreds

var (
	Package__ih9ch5 = &core.Package{
		PackageName: "namespacelabs.dev/foundation/universe/db/postgres/internal/gencreds",
	}

	Provider__ih9ch5 = core.Provider{
		Package:     Package__ih9ch5,
		Instantiate: makeDeps__ih9ch5,
	}
)

func makeDeps__ih9ch5(ctx context.Context, di core.Dependencies) (_ interface{}, err error) {
	var deps ExtensionDeps

	// name: "postgres-password-file"
	if deps.Password, err = secrets.ProvideSecret(ctx, core.MustUnwrapProto("ChZwb3N0Z3Jlcy1wYXNzd29yZC1maWxl", &secrets.Secret{}).(*secrets.Secret)); err != nil {
		return nil, err
	}

	return deps, nil
}
