load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "clerk",
    srcs = ["clerk.go"],
    importpath = "namespacelabs.dev/foundation/internal/clerk",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/fnerrors",
        "@com_github_spf13_pflag//:pflag",
    ],
)
