load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "admin",
    srcs = [
        "admin.go",
        "signpartnertoken.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/cli/cmd/admin",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/cli/fncobra",
        "//internal/fnerrors",
        "@com_github_golang_jwt_jwt_v4//:jwt",
        "@com_github_spf13_cobra//:cobra",
        "@com_github_spf13_pflag//:pflag",
    ],
)
