load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "init_lib",
    srcs = ["main.go"],
    importpath = "namespacelabs.dev/foundation/universe/development/localstack/s3/internal/managebuckets/init",
    visibility = ["//visibility:private"],
    deps = [
        "//universe/aws/s3",
        "//universe/development/localstack/s3",
    ],
)

go_binary(
    name = "init",
    embed = [":init_lib"],
    visibility = ["//universe/development/localstack/s3:__subpackages__"],
)
