load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "kubeblueprint",
    srcs = ["rbac.go"],
    importpath = "namespacelabs.dev/foundation/framework/kubernetes/kubeblueprint",
    visibility = ["//visibility:public"],
    deps = [
        "//framework/kubernetes/kubedef",
        "//framework/kubernetes/kubetool",
        "//framework/provisioning",
        "//framework/rpcerrors",
        "//internal/fnerrors",
        "@io_k8s_client_go//applyconfigurations/core/v1:core",
        "@io_k8s_client_go//applyconfigurations/rbac/v1:rbac",
        "@org_golang_google_grpc//codes",
    ],
)
