load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "tracing",
    srcs = [
        "deps.fn.go",
        "http.go",
        "metrics.go",
        "traceparent.go",
        "types.pb.go",
        "wire.go",
    ],
    importpath = "namespacelabs.dev/foundation/std/monitoring/tracing",
    visibility = ["//visibility:public"],
    deps = [
        "//schema",
        "//std/core/info",
        "//std/core/types",
        "//std/go/core",
        "//std/go/grpc/interceptors",
        "//std/go/http/middleware",
        "//std/monitoring/tracing/filter",
        "@com_github_google_uuid//:uuid",
        "@io_opentelemetry_go_contrib_instrumentation_google_golang_org_grpc_otelgrpc//:otelgrpc",
        "@io_opentelemetry_go_contrib_instrumentation_net_http_otelhttp//:otelhttp",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel//propagation",
        "@io_opentelemetry_go_otel//semconv/v1.40.0:v1_40_0",
        "@io_opentelemetry_go_otel_exporters_prometheus//:prometheus",
        "@io_opentelemetry_go_otel_exporters_stdout_stdouttrace//:stdouttrace",
        "@io_opentelemetry_go_otel_sdk//resource",
        "@io_opentelemetry_go_otel_sdk//trace",
        "@io_opentelemetry_go_otel_sdk_metric//:metric",
        "@io_opentelemetry_go_otel_trace//:trace",
        "@io_opentelemetry_go_otel_trace//noop",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//stats",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//runtime/protoimpl",
        "@org_golang_x_exp//slices",
    ],
)
