// This file is automatically generated.
package tracing

#Exports: {
	TraceProvider: {
		name?: string

		#Definition: {
			packageName: "namespacelabs.dev/foundation/std/monitoring/tracing"
			type:        "TraceProvider"
			typeDefinition: {
				"typename": "foundation.std.monitoring.tracing.TraceProviderArgs"
				"source": [
					"types.proto",
				]
			}
		}
	}
}
