// Copyright 2022 Namespace Labs Inc; All rights reserved.
// Licensed under the EARLY ACCESS SOFTWARE LICENSE AGREEMENT
// available at http://github.com/namespacelabs/foundation

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: runtime/kubernetes/client/clientconfig.proto

// XXX retaining package to avoid breaking existing configurations.

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostEnv struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kubeconfig string `protobuf:"bytes,1,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"`
	Context    string `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"` // If empty, uses default context.
}

func (x *HostEnv) Reset() {
	*x = HostEnv{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_kubernetes_client_clientconfig_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostEnv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostEnv) ProtoMessage() {}

func (x *HostEnv) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_kubernetes_client_clientconfig_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostEnv.ProtoReflect.Descriptor instead.
func (*HostEnv) Descriptor() ([]byte, []int) {
	return file_runtime_kubernetes_client_clientconfig_proto_rawDescGZIP(), []int{0}
}

func (x *HostEnv) GetKubeconfig() string {
	if x != nil {
		return x.Kubeconfig
	}
	return ""
}

func (x *HostEnv) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type SystemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodePlatform         []string `protobuf:"bytes,1,rep,name=node_platform,json=nodePlatform,proto3" json:"node_platform,omitempty"`
	DetectedDistribution string   `protobuf:"bytes,2,opt,name=detected_distribution,json=detectedDistribution,proto3" json:"detected_distribution,omitempty"` // k3d, eks, etc.
	EksClusterName       string   `protobuf:"bytes,3,opt,name=eks_cluster_name,json=eksClusterName,proto3" json:"eks_cluster_name,omitempty"`                 // Only set if distribution is eks.
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_kubernetes_client_clientconfig_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_kubernetes_client_clientconfig_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_runtime_kubernetes_client_clientconfig_proto_rawDescGZIP(), []int{1}
}

func (x *SystemInfo) GetNodePlatform() []string {
	if x != nil {
		return x.NodePlatform
	}
	return nil
}

func (x *SystemInfo) GetDetectedDistribution() string {
	if x != nil {
		return x.DetectedDistribution
	}
	return ""
}

func (x *SystemInfo) GetEksClusterName() string {
	if x != nil {
		return x.EksClusterName
	}
	return ""
}

var File_runtime_kubernetes_client_clientconfig_proto protoreflect.FileDescriptor

var file_runtime_kubernetes_client_clientconfig_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e,
	0x65, 0x74, 0x65, 0x73, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d,
	0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x2e, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x22, 0x43, 0x0a,
	0x07, 0x48, 0x6f, 0x73, 0x74, 0x45, 0x6e, 0x76, 0x12, 0x1e, 0x0a, 0x0a, 0x6b, 0x75, 0x62, 0x65,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6b, 0x75,
	0x62, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x22, 0x90, 0x01, 0x0a, 0x0a, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x6f, 0x64, 0x65, 0x50, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x33, 0x0a, 0x15, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x65, 0x64, 0x44,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x10, 0x65,
	0x6b, 0x73, 0x5f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x65, 0x6b, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x38, 0x5a, 0x36, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x6c, 0x61, 0x62, 0x73, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x66, 0x6f, 0x75, 0x6e, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x6b, 0x75,
	0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_runtime_kubernetes_client_clientconfig_proto_rawDescOnce sync.Once
	file_runtime_kubernetes_client_clientconfig_proto_rawDescData = file_runtime_kubernetes_client_clientconfig_proto_rawDesc
)

func file_runtime_kubernetes_client_clientconfig_proto_rawDescGZIP() []byte {
	file_runtime_kubernetes_client_clientconfig_proto_rawDescOnce.Do(func() {
		file_runtime_kubernetes_client_clientconfig_proto_rawDescData = protoimpl.X.CompressGZIP(file_runtime_kubernetes_client_clientconfig_proto_rawDescData)
	})
	return file_runtime_kubernetes_client_clientconfig_proto_rawDescData
}

var file_runtime_kubernetes_client_clientconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_runtime_kubernetes_client_clientconfig_proto_goTypes = []interface{}{
	(*HostEnv)(nil),    // 0: foundation.runtime.kubernetes.HostEnv
	(*SystemInfo)(nil), // 1: foundation.runtime.kubernetes.SystemInfo
}
var file_runtime_kubernetes_client_clientconfig_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runtime_kubernetes_client_clientconfig_proto_init() }
func file_runtime_kubernetes_client_clientconfig_proto_init() {
	if File_runtime_kubernetes_client_clientconfig_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_runtime_kubernetes_client_clientconfig_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostEnv); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_kubernetes_client_clientconfig_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_runtime_kubernetes_client_clientconfig_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_runtime_kubernetes_client_clientconfig_proto_goTypes,
		DependencyIndexes: file_runtime_kubernetes_client_clientconfig_proto_depIdxs,
		MessageInfos:      file_runtime_kubernetes_client_clientconfig_proto_msgTypes,
	}.Build()
	File_runtime_kubernetes_client_clientconfig_proto = out.File
	file_runtime_kubernetes_client_clientconfig_proto_rawDesc = nil
	file_runtime_kubernetes_client_clientconfig_proto_goTypes = nil
	file_runtime_kubernetes_client_clientconfig_proto_depIdxs = nil
}
