load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "ns",
    srcs = ["main.go"],
    importpath = "namespacelabs.dev/foundation/internal/cli/fncobra/ns",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/artifacts/oci",
        "//internal/build/binary",
        "//internal/build/binary/genbinary",
        "//internal/build/buildkit",
        "//internal/cli/fncobra",
        "//internal/codegen",
        "//internal/codegen/genpackage",
        "//internal/compute",
        "//internal/console",
        "//internal/environment",
        "//internal/filewatcher",
        "//internal/fnapi",
        "//internal/frontend/cuefrontend/entity",
        "//internal/frontend/cuefrontend/integration/api",
        "//internal/frontend/cuefrontend/integration/dockerfile",
        "//internal/frontend/cuefrontend/integration/golang",
        "//internal/frontend/cuefrontend/integration/shellscript",
        "//internal/git",
        "//internal/integrations/golang",
        "//internal/integrations/opaque",
        "//internal/llbutil",
        "//internal/networking/ingress",
        "//internal/networking/ingress/nginx",
        "//internal/parsing/integration/dockerfile",
        "//internal/parsing/integration/golang",
        "//internal/parsing/integration/shellscript",
        "//internal/planning/deploy",
        "//internal/planning/tool",
        "//internal/providers/nscloud",
        "//internal/providers/nscloud/nsingress",
        "//internal/providers/onepassword",
        "//internal/runtime",
        "//internal/runtime/kubernetes",
        "//internal/runtime/kubernetes/helm",
        "//internal/runtime/kubernetes/kubeops",
        "//internal/sdk/gcloud",
        "//internal/sdk/k3d",
        "//internal/testing",
        "//orchestration",
        "//orchestration/client",
        "//schema",
        "//std/cfg",
        "//std/module",
        "//std/plugandplay",
        "//universe/aws/iam",
        "@com_github_spf13_cobra//:cobra",
    ],
)
