// Copyright 2022 Namespace Labs Inc; All rights reserved.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: schema/storage/diagnostics.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvironmentDiagnostics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Runtime         string       `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	RuntimeSpecific []*anypb.Any `protobuf:"bytes,2,rep,name=runtime_specific,json=runtimeSpecific,proto3" json:"runtime_specific,omitempty"`
}

func (x *EnvironmentDiagnostics) Reset() {
	*x = EnvironmentDiagnostics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_storage_diagnostics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnvironmentDiagnostics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentDiagnostics) ProtoMessage() {}

func (x *EnvironmentDiagnostics) ProtoReflect() protoreflect.Message {
	mi := &file_schema_storage_diagnostics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentDiagnostics.ProtoReflect.Descriptor instead.
func (*EnvironmentDiagnostics) Descriptor() ([]byte, []int) {
	return file_schema_storage_diagnostics_proto_rawDescGZIP(), []int{0}
}

func (x *EnvironmentDiagnostics) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *EnvironmentDiagnostics) GetRuntimeSpecific() []*anypb.Any {
	if x != nil {
		return x.RuntimeSpecific
	}
	return nil
}

var File_schema_storage_diagnostics_proto protoreflect.FileDescriptor

var file_schema_storage_diagnostics_proto_rawDesc = []byte{
	0x0a, 0x20, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x2f, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x19, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x1a, 0x19, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61,
	0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x73, 0x0a, 0x16, 0x45, 0x6e, 0x76, 0x69,
	0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69,
	0x63, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x3f, 0x0a, 0x10,
	0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x0f, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x42, 0x2d, 0x5a,
	0x2b, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6c, 0x61, 0x62, 0x73, 0x2e, 0x64,
	0x65, 0x76, 0x2f, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schema_storage_diagnostics_proto_rawDescOnce sync.Once
	file_schema_storage_diagnostics_proto_rawDescData = file_schema_storage_diagnostics_proto_rawDesc
)

func file_schema_storage_diagnostics_proto_rawDescGZIP() []byte {
	file_schema_storage_diagnostics_proto_rawDescOnce.Do(func() {
		file_schema_storage_diagnostics_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_storage_diagnostics_proto_rawDescData)
	})
	return file_schema_storage_diagnostics_proto_rawDescData
}

var file_schema_storage_diagnostics_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schema_storage_diagnostics_proto_goTypes = []interface{}{
	(*EnvironmentDiagnostics)(nil), // 0: foundation.schema.storage.EnvironmentDiagnostics
	(*anypb.Any)(nil),              // 1: google.protobuf.Any
}
var file_schema_storage_diagnostics_proto_depIdxs = []int32{
	1, // 0: foundation.schema.storage.EnvironmentDiagnostics.runtime_specific:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_schema_storage_diagnostics_proto_init() }
func file_schema_storage_diagnostics_proto_init() {
	if File_schema_storage_diagnostics_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schema_storage_diagnostics_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnvironmentDiagnostics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_storage_diagnostics_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_storage_diagnostics_proto_goTypes,
		DependencyIndexes: file_schema_storage_diagnostics_proto_depIdxs,
		MessageInfos:      file_schema_storage_diagnostics_proto_msgTypes,
	}.Build()
	File_schema_storage_diagnostics_proto = out.File
	file_schema_storage_diagnostics_proto_rawDesc = nil
	file_schema_storage_diagnostics_proto_goTypes = nil
	file_schema_storage_diagnostics_proto_depIdxs = nil
}
