load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "secrets",
    srcs = ["secretserialization.go"],
    importpath = "namespacelabs.dev/foundation/internal/secrets",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/kubernetes/kubenaming",
        "//library/runtime",
        "//schema",
        "@org_golang_google_protobuf//encoding/protojson",
    ],
)
