load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "auth",
    srcs = [
        "awscognito.go",
        "checkauth.go",
        "checklogin.go",
        "circlecitoken.go",
        "clientcert.go",
        "cmd.go",
        "devtoken.go",
        "githubtoken.go",
        "impersonatetenant.go",
        "login.go",
        "logout.go",
        "oidc.go",
        "oidctoken.go",
        "trust.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/cli/cmd/auth",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/auth",
        "//internal/circleci",
        "//internal/cli/cmd/cluster",
        "//internal/cli/cmd/token",
        "//internal/cli/fncobra",
        "//internal/console",
        "//internal/fnapi",
        "//internal/fnerrors",
        "//internal/github",
        "//internal/github/env",
        "@com_github_aws_aws_sdk_go_v2//aws",
        "@com_github_aws_aws_sdk_go_v2_config//:config",
        "@com_github_aws_aws_sdk_go_v2_service_cognitoidentity//:cognitoidentity",
        "@com_github_dustin_go_humanize//:go-humanize",
        "@com_github_morikuni_aec//:aec",
        "@com_github_pkg_browser//:browser",
        "@com_github_spf13_cobra//:cobra",
        "@dev_namespacelabs_integrations//proto/namespace/cloud/iam/v1beta",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)
