// This file was automatically generated by Namespace.
// DO NOT EDIT. To update, re-run `ns generate`.

package legacycontroller

import (
	"context"
	fncore "namespacelabs.dev/foundation/std/core"
	"namespacelabs.dev/foundation/std/go/core"
)

// Dependencies that are instantiated once for the lifetime of the extension.
type ExtensionDeps struct {
	Ready core.Check
}

var (
	Package__6uudga = &core.Package{
		PackageName: "namespacelabs.dev/foundation/internal/orchestration/legacycontroller",
	}

	Provider__6uudga = core.Provider{
		Package:     Package__6uudga,
		Instantiate: makeDeps__6uudga,
	}

	Initializers__6uudga = []*core.Initializer{
		{
			Package: Package__6uudga,
			Do: func(ctx context.Context, di core.Dependencies) error {
				return di.Instantiate(ctx, Provider__6uudga, func(ctx context.Context, v interface{}) error {
					return Prepare(ctx, v.(ExtensionDeps))
				})
			},
		},
	}
)

func makeDeps__6uudga(ctx context.Context, di core.Dependencies) (_ interface{}, err error) {
	var deps ExtensionDeps

	if deps.Ready, err = fncore.ProvideReadinessCheck(ctx, nil); err != nil {
		return nil, err
	}

	return deps, nil
}
