load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "kubeops",
    srcs = [
        "checkresource.go",
        "kubeops.go",
        "op_apply.go",
        "op_applyrolebinding.go",
        "op_cleanupruntimeconfig.go",
        "op_create.go",
        "op_createsecret.go",
        "op_delete.go",
        "op_deletelist.go",
        "op_ensuredeployment.go",
        "op_ensureruntimeconfig.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/runtime/kubernetes/kubeops",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/kubernetes/kubeblueprint",
        "//framework/kubernetes/kubedef",
        "//framework/kubernetes/kubeobj",
        "//framework/kubernetes/kubeparser",
        "//framework/kubernetes/kubetool",
        "//framework/resources",
        "//framework/rpcerrors/multierr",
        "//internal/console",
        "//internal/fnerrors",
        "//internal/networking/ingress",
        "//internal/planning/deploy",
        "//internal/runtime",
        "//internal/runtime/kubernetes",
        "//internal/runtime/kubernetes/client",
        "//internal/runtime/kubernetes/kubeobserver",
        "//internal/tools/maketlscert",
        "//schema",
        "//schema/orchestration",
        "//schema/runtime",
        "//std/execution",
        "//std/tasks",
        "//std/types",
        "@io_k8s_api//apps/v1:apps",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_apiextensions_apiserver//pkg/apis/apiextensions/v1:apiextensions",
        "@io_k8s_apiextensions_apiserver//pkg/client/clientset/clientset/typed/apiextensions/v1:apiextensions",
        "@io_k8s_apimachinery//pkg/api/errors",
        "@io_k8s_apimachinery//pkg/api/meta",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/apis/meta/v1/unstructured",
        "@io_k8s_apimachinery//pkg/runtime/schema",
        "@io_k8s_apimachinery//pkg/types",
        "@io_k8s_apimachinery//pkg/watch",
        "@io_k8s_client_go//applyconfigurations/core/v1:core",
        "@io_k8s_client_go//applyconfigurations/rbac/v1:rbac",
        "@io_k8s_client_go//discovery",
        "@io_k8s_client_go//kubernetes",
        "@io_k8s_client_go//rest",
        "@io_k8s_client_go//restmapper",
        "@org_golang_google_protobuf//encoding/protojson",
        "@org_golang_google_protobuf//types/known/timestamppb",
    ],
)
