// This file is automatically generated.
package rds

import (
	"namespacelabs.dev/foundation/std/fn:types"
)

#Exports: {
	Database: {
		name?:       string
		schemaFile?: types.#Resource

		#Definition: {
			packageName: "namespacelabs.dev/foundation/universe/db/postgres/rds"
			type:        "Database"
			typeDefinition: {
				"typename": "foundation.universe.db.postgres.rds.Database"
				"source": [
					"provider.proto",
				]
			}
		}
	}
}
