load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "debugshell",
    srcs = ["image.go"],
    importpath = "namespacelabs.dev/foundation/internal/debugshell",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/artifacts/oci",
        "//internal/build",
        "//internal/build/buildkit",
        "//internal/build/multiplatform",
        "//internal/compute",
        "//internal/llbutil",
        "//schema",
        "//std/pkggraph",
        "@com_github_moby_buildkit//client/llb",
        "@com_github_moby_buildkit//util/system",
        "@com_github_opencontainers_image_spec//specs-go/v1:specs-go",
    ],
)
