load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "parsing",
    srcs = [
        "binary.go",
        "canonicalize.go",
        "closure.go",
        "handler.go",
        "json.go",
        "list.go",
        "loader.go",
        "module.go",
        "node.go",
        "package.go",
        "protos.go",
        "provider.go",
        "resourceclass.go",
        "resourceinstance.go",
        "resourceprovider.go",
        "root.go",
        "server.go",
        "test.go",
        "validation.go",
        "workspace.go",
    ],
    importpath = "namespacelabs.dev/foundation/internal/parsing",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/findroot",
        "//framework/kubernetes/kubenaming",
        "//framework/rpcerrors/multierr",
        "//internal/artifacts/download",
        "//internal/cli/fncobra/name",
        "//internal/codegen/protos",
        "//internal/compute",
        "//internal/console",
        "//internal/fnerrors",
        "//internal/fnfs",
        "//internal/fnfs/zipfs",
        "//internal/git",
        "//internal/localexec",
        "//internal/parsing/integration/api",
        "//internal/parsing/invariants",
        "//internal/protos",
        "//internal/versions",
        "//internal/workspace",
        "//internal/workspace/dirs",
        "//schema",
        "//std/cfg",
        "//std/pkggraph",
        "//std/resources",
        "//std/tasks",
        "@dev_namespacelabs_go_ids//:go-ids",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//reflect/protodesc",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//types/known/anypb",
        "@org_golang_x_exp//maps",
        "@org_golang_x_exp//slices",
        "@org_golang_x_net//html",
        "@org_golang_x_sync//errgroup",
    ],
)
