// This file was automatically generated by Namespace.
// DO NOT EDIT. To update, re-run `ns generate`.

package info

import (
	"context"
	"namespacelabs.dev/foundation/std/core/types"
	"namespacelabs.dev/foundation/std/go/core"
)

type _checkProvideServerInfo func(context.Context, *ServerInfoArgs) (*types.ServerInfo, error)

var _ _checkProvideServerInfo = ProvideServerInfo

var (
	Package__e86rl8 = &core.Package{
		PackageName: "namespacelabs.dev/foundation/std/core/info",
	}
)
