// This file is automatically generated.
package info

#Exports: {
	ServerInfo: {
		#Definition: {
			packageName: "namespacelabs.dev/foundation/std/core/info"
			type:        "ServerInfo"
			typeDefinition: {
				"typename": "foundation.std.core.types.ServerInfoArgs"
				"source": [
					"../types/coretypes.proto",
				]
			}
		}
	}
}
