load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "readiness",
    srcs = ["readiness.go"],
    importpath = "namespacelabs.dev/foundation/internal/runtime/kubernetes/readiness",
    visibility = ["//:__subpackages__"],
    deps = [
        "//framework/kubernetes/kubeobj",
        "//internal/fnerrors",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_client_go//kubernetes",
        "@io_k8s_client_go//rest",
    ],
)
