load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "orchestration",
    srcs = [
        "env.go",
        "migration.go",
        "prepare.go",
        "slack.go",
    ],
    importpath = "namespacelabs.dev/foundation/orchestration",
    visibility = ["//visibility:public"],
    deps = [
        "//framework/kubernetes/kubedef",
        "//framework/kubernetes/kubetool",
        "//framework/secrets",
        "//framework/secrets/combined",
        "//internal/build/binary",
        "//internal/compute",
        "//internal/console",
        "//internal/fnerrors",
        "//internal/parsing",
        "//internal/planning",
        "//internal/planning/deploy",
        "//internal/planning/secrets",
        "//internal/protos",
        "//internal/runtime",
        "//internal/runtime/kubernetes/client",
        "//orchestration/client",
        "//orchestration/server/constants",
        "//schema",
        "//schema/runtime",
        "//std/cfg",
        "//std/execution",
        "//std/tasks",
        "@com_github_slack_go_slack//:slack",
        "@io_k8s_utils//strings/slices",
        "@org_golang_google_protobuf//proto",
    ],
)
