load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "tasks",
    srcs = [
        "actions.go",
        "attachments.go",
        "configuration.pb.go",
        "context.go",
        "errors.go",
        "flags.go",
        "logging.go",
        "sink.go",
        "stacktrace.go",
        "stateful.go",
        "store.go",
        "task.go",
        "throttle.go",
    ],
    importpath = "namespacelabs.dev/foundation/std/tasks",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/environment",
        "//internal/fnerrors",
        "//internal/fnerrors/stacktrace",
        "//internal/sync",
        "//internal/workspace/dirs",
        "//schema",
        "//schema/storage",
        "//std/tasks/actiontracing",
        "//std/tasks/idtypes",
        "//std/tasks/protocol",
        "@com_github_kr_text//:text",
        "@com_github_spf13_pflag//:pflag",
        "@dev_namespacelabs_go_ids//:go-ids",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel//codes",
        "@io_opentelemetry_go_otel_trace//:trace",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//encoding/prototext",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//reflect/protoregistry",
        "@org_golang_google_protobuf//runtime/protoimpl",
        "@sh_helm_helm_v3//pkg/time",
    ],
)
