name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN : ${{ secrets.CLA_GITHUB_TOKEN }}
        with:
          remote-organization-name: 'namespacelabs'
          remote-repository-name: 'cla'
          path-to-signatures: 'v2023-06-06/signatures.json'
          path-to-document: 'https://github.com/namespacelabs/cla/blob/main/README.md'
          # branch should not be protected
          branch: 'main'
          allowlist: dependabot*
