name: static-analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  gofmt:
    runs-on: nscloud-ubuntu-22.04-amd64-2x8
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Run gofmt (goimports)
        run: go run golang.org/x/tools/cmd/goimports -d --format-only .
      - name: Breakpoint on failure
        if: failure() && github.ref_name == 'main'
        uses: namespacelabs/breakpoint-action@v0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          duration: 15m
          authorized-users: edganiukov,hugosantos,n-g,htr,nichtverstehen,gmichelo
          slack-announce-channel: "#ci"

  vet:
    runs-on: nscloud-ubuntu-22.04-amd64-2x8
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run go vet
        run: go vet ./...
      - name: Breakpoint on failure
        if: failure() && github.ref_name == 'main'
        uses: namespacelabs/breakpoint-action@v0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          duration: 15m
          authorized-users: edganiukov,hugosantos,n-g,htr,nichtverstehen,gmichelo
          slack-announce-channel: "#ci"

  staticcheck:
    runs-on: nscloud
    strategy:
      matrix:
        goos: [linux] # Not running darwin due to it requiring the C integration.
        goarch: [amd64, arm64]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install staticcheck
        run: "go install honnef.co/go/tools/cmd/staticcheck"

      - name: Print staticcheck version
        run: "staticcheck -version"

      - name: "Run staticcheck (${{ matrix.goos }}/${{ matrix.goarch }})"
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: "staticcheck ./..."

      - name: Breakpoint on failure
        if: failure() && github.ref_name == 'main'
        uses: namespacelabs/breakpoint-action@v0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          duration: 15m
          authorized-users: edganiukov,hugosantos,n-g,htr,nichtverstehen,gmichelo
          slack-announce-channel: "#ci"
