load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "pkggraph",
    srcs = [
        "binary.go",
        "checkload.go",
        "context.go",
        "frontenddata.go",
        "injections.go",
        "loader.go",
        "location.go",
        "module.go",
        "package.go",
        "validatefoundation.go",
        "workspacedata.go",
    ],
    importpath = "namespacelabs.dev/foundation/std/pkggraph",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/codegen/protos",
        "//internal/compute",
        "//internal/console",
        "//internal/fnerrors",
        "//internal/fnfs",
        "//internal/git",
        "//internal/versions",
        "//internal/workspace",
        "//schema",
        "//schema/runtime",
        "//std/cfg",
        "//std/execution",
        "//std/types",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//reflect/protoregistry",
        "@org_golang_google_protobuf//types/known/anypb",
        "@org_golang_x_net//context",
    ],
)
