load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "onepassword",
    srcs = ["types.pb.go"],
    importpath = "namespacelabs.dev/foundation/universe/onepassword",
    visibility = ["//visibility:public"],
    deps = [
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//runtime/protoimpl",
    ],
)
