# slimmer than gitpod/workspace-full, includes base, Go, Docker and Tailscale.
FROM gitpod/workspace-go

USER gitpod

# 1. Adding "/" to the PATH so "ns" can be found: "go_build" doesn't allow to specify the target dir.
#
# 2. Adding current $PATH to .bashrc so it survives "layer_build_plan" merging that copies only files
#    from layers but not environment variables.
RUN echo "export PATH=${PATH}:/:\$PATH" > $HOME/.bashrc.d/ns-path
