load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "compatibility",
    srcs = ["check.go"],
    importpath = "namespacelabs.dev/foundation/internal/planning/compatibility",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/fnerrors/env",
        "//schema",
    ],
)
